### ISSUE TITLE
第一版主网

### ISSUE THREAD

**Issue by bea452awqqw** [404-novel-project/novel-downloader#113]
- 站点名称：第一版主网
- 站点URL：http://www.diyibanzhu333.xyz/
- 站点类型： 转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：无
- 希望添加的理由：此网站是第一版主网的众多域名之一，此网站除了有着其他网站都有的一般小说之外还有一些成年人看了会激动不已的福利小说
- 你认为该站值得阅读的书籍：人类拯救计划

**Comment by yingziwu** [comment]
书源质量不高，有大量图片，非原创网站。
