### ISSUE TITLE
bug：Pixiv小说无法滚屏

### ISSUE THREAD

**Issue by XYLSBJ** [404-novel-project/novel-downloader#146]
- 站点名称：pixiv
- 站点URL：https://www.pixiv.net/novel/
- 站点类型：原创网站 / 转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：代理
投票窗口与非公开收藏窗口弹出来后很快消失，接着滚动栏消失无法滚动屏幕，关掉脚本后一切正常。

**Comment by yingziwu** [comment]
出问题的网址URL？

**Comment by XYLSBJ** [comment]
> 出问题的网址URL？

在我这每个小说页面都是一样的
![{8B026281-D4BB-4F20-8A90-8B10C7DC4E86}](https://user-images.githubusercontent.com/99113920/152673794-e3bf03da-5320-430b-a833-2a9d2ef6f21c.png)
![{38AB385D-07BD-42DF-9FA4-6FECC0995728}](https://user-images.githubusercontent.com/99113920/152673795-54036ee3-50d3-4e1e-b86c-c922cfa67e76.png)
右边的滚动栏消失然后无法滚动，必须刷新

**Comment by XYLSBJ** [comment]
[https://www.pixiv.net/novel/show.php?id=14327047](url)
示范页面

**Comment by yingziwu** [comment]
更新了一下，试一试最新版看一看

**Comment by XYLSBJ** [comment]
已解决
