### ISSUE TITLE
废文简介带图片的文运行脚本报错

### ISSUE THREAD

**Issue by ryanlo713** [404-novel-project/novel-downloader#164]
具体情况请见日志。

[novel-downloader-1644867823097.log](https://github.com/404-novel-project/novel-downloader/files/8063522/novel-downloader-1644867823097.log)
[novel-downloader-1644867178232.log](https://github.com/404-novel-project/novel-downloader/files/8063531/novel-downloader-1644867178232.log)

**Comment by yingziwu** [comment]
无法复现
