### ISSUE TITLE
运行过程出错，调试能正常获取

### ISSUE THREAD

**Issue by flybywind-1986** [404-novel-project/novel-downloader#181]
[Init]开始载入小说下载器……
[Init]当前时间：2022-03-03T14:01:19.137Z
[Init]当前页URL：https://www.cool18.com/bbs4/index.php?app=forum&act=threadview&tid=14237259
[Init]workerId：35d1647d-f74c-4116-8d6b-17978a3e65e5
[Init]当前页Referrer：https://www.cool18.com/bbs4/
[Init]浏览器UA：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.30
[Init]浏览器语言：zh-CN,en,en-GB,en-US
[Init]设备运行平台：Win32
[Init]设备内存：8
[Init]CPU核心数：12
[Init]eval：true, 33
[Init]fetch：true, 44
[Init]XMLHttpRequest：true, 43
[Init]streamSupport：true
[Init]window：280
[Init]localStorage：true
[Init]sessionStorage：true
[Init]Cookie：true
[Init]doNotTrack：1
[Init]enableDebug：false
[Init]ScriptHandler：Violentmonkey
[Init]ScriptHandler version：2.12.7
[Init]Novel-downloader version：4.8.3.619
[run]下载开始
[]
[preTest]nowRunning: 0
[fflateZip] filename: [大阴雄]异界猎妈人.epub, stream: false, streamSaver.supported: true
TypeErrorCannot read properties of undefined (reading 'get')TypeError: Cannot read properties of undefined (reading 'get')
    at saveHook (chrome-extension://jeokchcoaikafalmgagcpcgcfiplcdpd/%E5%B0%8F%E8%AF%B4%E4%B8%8B%E8%BD%BD%E5%99%A8.user.js#44:13735:44)
    at Cool18.run (chrome-extension://jeokchcoaikafalmgagcpcgcfiplcdpd/%E5%B0%8F%E8%AF%B4%E4%B8%8B%E8%BD%BD%E5%99%A8.user.js#44:13690:19)
    at async run (chrome-extension://jeokchcoaikafalmgagcpcgcfiplcdpd/%E5%B0%8F%E8%AF%B4%E4%B8%8B%E8%BD%BD%E5%99%A8.user.js#44:26333:17)运行过程出错，请附上相关日志至支持地址进行反馈。
支持地址：https://github.com/yingziwu/novel-downloader

**Comment by yingziwu** [comment]
![image](https://user-images.githubusercontent.com/22741471/156778105-0b981807-4029-48c8-b1c2-d3ec70158102.png)
为有一点奇怪，按理来说不会出现这个问题的呀！

我本地使用 Chromium 99.0.4844.51 + Violentmonkey 2.13.0 也没能复现。

**Comment by yingziwu** [comment]
你可以创建一个纯净的环净测试一下吗？

**Comment by flybywind-1986** [comment]
我用的edge版本 99.0.1150.30 (官方内部版本) beta (64 位)，怎么弄都不行，重新下了chrome就可以了，谢谢大大
