### ISSUE TITLE
第一次用，脚本加载失败是什么情况

### ISSUE THREAD

**Issue by yunv7** [404-novel-project/novel-downloader#182]
![image](https://user-images.githubusercontent.com/85724850/156684623-18453fdc-24e3-4fa8-be5e-121e29b24ffc.png)

Cent Browser
版本 3.9.2.45（正式版本） （32 位） (Chromium 72.0.3626.121)
tampermonkey 4.13

**Comment by yingziwu** [comment]
> Chromium 72.0.3626.121

浏览器版本太低了

![image](https://user-images.githubusercontent.com/22741471/156685624-9068083f-8689-46cd-9429-1a8b3d6281f1.png)
https://github.com/404-novel-project/novel-downloader/blob/master/src/header.json#L17-L23
