### ISSUE TITLE
站点请求：有毒小说网

### ISSUE THREAD

**Issue by fsywxj111** [404-novel-project/novel-downloader#197]
- 站点名称：有毒小说网
- 站点URL：https://www.youdubook.com
- 站点类型：原创网站
- 有无收费章节：有
- 有无如登录墙等额外限制：无
- 希望添加的理由：下载小说
- 你认为该站值得阅读的书籍：欧陆无双马友夫

**Comment by cxumol** [comment]
- 你认为该站值得阅读的书籍：赛博剑仙铁雨
