### ISSUE TITLE
站点请求：少年梦阅读

### ISSUE THREAD

**Issue by cxumol** [404-novel-project/novel-downloader#205]
- 站点名称：少年梦阅读
- 站点URL：https://www.shaoniandream.com/ | https://h5.shaoniandream.com/
- 站点类型：原创网站
- 有无收费章节：有
- 有无如登录墙等额外限制：暂无
- 希望添加的理由：小站倒闭可能性更高, 需要存档; 有毒小说网第二任主编自立门户, 带着一些编辑和作者出逃了
- 你认为该站值得阅读的书籍：[深空恐惧2277](https://www.shaoniandream.com/book_detail/722)

**Comment by yeguang666c** [comment]
1

**Comment by gin32167** [comment]
同求这个站点
