### ISSUE TITLE
站点请求：轻书架

### ISSUE THREAD

**Issue by HMSRenown** [404-novel-project/novel-downloader#214]
- 站点名称：轻书架
- 站点URL：https://www.lightnovel.app
- 站点类型：转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：有
- 希望添加的理由：有诸多轻小说资源
- 你认为该站值得阅读的书籍：学战都市Asterisk

**Comment by tiansh** [comment]
搞了一个下载的脚本，弄得有点复杂，所以不是用的这个的框架，你要是需要可以试试
https://github.com/tiansh/qingshujia-txt-download

**Comment by ldm0206** [comment]
有邀请码的话可以试试，很少见到还在用第一版material design的网站了，不过看到网站公告里有这样一句"假设真白和LK都像轻书架一样，对所有的书上一套字体加密"，得看一下他具体是怎么做的

**Comment by tiansh** [comment]
@ldm0206 我现在没有账号，所以是基于旧版的逻辑讨论的：

* 网页指定了文字的字体文件，这个字体文件可以直接下载下来，然后找个工具把字体里的每个字转换成轮廓。
* 字体文件是基于某个现成的字体做的（而且有大约100.0%的几率这个字体版权是有问题的），所以文字轮廓和这个字体的文字完全一致。
* 基于逐个轮廓的对比，可以找到这个字体里和他所有完全匹配的点位都有哪些（很可能不唯一）
* 对于不唯一的，参考[这个列表](https://www.unicode.org/Public/security/15.0.0/confusables.txt)选择最合适的字符

**Comment by ldm0206** [comment]
> @ldm0206 我现在没有账号，所以是基于旧版的逻辑讨论的：
> 
> * 网页指定了文字的字体文件，这个字体文件可以直接下载下来，然后找个工具把字体里的每个字转换成轮廓。
> * 字体文件是基于[某个现成的字体](https://www.onlinewebfonts.com/download/796a8aac411b7d0cce8b49865160eb63)做的（而且有大约100.0%的几率这个字体版权是有问题的），所以文字轮廓和这个字体的文字完全一致。
> * 基于逐个轮廓的对比，可以找到这个字体里和他所有完全匹配的点位都有哪些（很可能不唯一）
> * 对于不唯一的，参考[这个列表](https://www.unicode.org/Public/security/15.0.0/confusables.txt)选择最合适的字符

看起来和晋江、知乎的做法差不多，如果要用脚本实现的话就得去预先匹配字体库，这样的话需要额外的开支和维护，像本脚本现在使用的远程字体匹配功能实际上已经很久不能正常工作了。

另外我看了一下，这个网站似乎并没有app版。想找API请求的办法也不太可行了。我之前做知乎的时候用的开源工具截图OCR，识别效果也很好，只是这种都需要做成客户端。（知乎防盗更严，发现请求异常就直接封号，因此不太适合做成公开软件分享，免得反而给开发者自身惹一身骚）
