### ISSUE TITLE
[Bug]: 所有网站不显示下载图标

### ISSUE THREAD

**Issue by darkelfzdy** [404-novel-project/novel-downloader#219]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [x] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [ ] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [ ] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [ ] 小说下载器脚本是唯一用户脚本

### 问题描述

我使用的是360极速浏览器X（21.0.1082.0），下载脚本也是最新版的。但是不显示下载图标。如果倒退会比较早的版本就没有这个问题

### 问题发生的网址：

https://www.imiaobige.com/read/38398/

### 复现步骤

x

### 期待的行为

x

### 实际的行为

x

### 小说下载器脚本版本

4.8.3.655

### 脚本管理器（Tampermonkey/Violentmonkey）版本

4.13

### 浏览器名称及版本

306极速浏览器X（21.0.1082.0）

**Comment by yingziwu** [comment]
可以按下 F12 打开 Cosole (控制台)，把里面的日志复制一下吗？

306极速浏览器X 使用的是 Chromium 95 内核，按理而言不应该出现无法运行这个问题的。

**Comment by yingziwu** [comment]
> userscript.html?name=%E5%B0%8F%E8%AF%B4%E4%B8%8B%E8%BD%BD%E5%99%A8.user.js&id=c100976a-90d4-434c-a053-e755a1c21b1d:2 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/crypto-js@4.1.1/crypto-js.js#sha512-NQVmLzNy4Lr5QTrmXvq/WzTMUnRHmv7nyIT/M6LyGPBS+TIeRxZ+YQaqWxjpRpvRMQSuYPQURZz/+pLi81xXeA==

>  userscript.html?name=%E5%B0%8F%E8%AF%B4%E4%B8%8B%E8%BD%BD%E5%99%A8.user.js&id=c100976a-90d4-434c-a053-e755a1c21b1d:4 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/fflate@0.7.3/umd/index.js#sha512-F57jcpLWPENXlHrsEj+YC8m+IHvaoRZpCpDr7Tfvu/jRtuO7kPOfbsop2gXEIRoK66ETYamk1tlTEvNw6xE8jw==

>  userscript.html?name=%E5%B0%8F%E8%AF%B4%E4%B8%8B%E8%BD%BD%E5%99%A8.user.js&id=c100976a-90d4-434c-a053-e755a1c21b1d:8 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/vue@3.2.31/dist/vue.global.prod.js#sha512-DB4qKu3/TbfQPJoPrMizkEHEA4biclKAhCFvLN6d2/zVvHOBS8aI/p8oYQgpWPHyDn6UdSJMdt+mqUCDWxLYWQ==

网络问题，无法访问 jsdelivr CDN

**Comment by darkelfzdy** [comment]
确实可能是本地网络的问题，我换了edge试了一下，也不行。看来只有把版本往回退才可以了

**Comment by darkelfzdy** [comment]
这种本地网络有可能是什么原因造成的呢？有没有办法解决呢？

**Comment by darkelfzdy** [comment]
我刚才测试了一下，我用本地的有线网络确实无法访问cdn.jsdelivr.net （但可以ping通），然后用手机4G网络就可以正常访问cdn.jsdelivr.net 。太操蛋了

**Comment by darkelfzdy** [comment]
我在网上搜索了一下，好像说cdn.jsdelivr.net 在某些节点就是挂了

**Comment by lisansas** [comment]
> 我在网上搜索了一下，好像说cdn.jsdelivr.net 在某些节点就是挂了

没挂，间歇性墙，和github一样。

**Comment by yingziwu** [comment]
> 我刚才测试了一下，我用本地的有线网络确实无法访问cdn.jsdelivr.net （但可以ping通），然后用手机4G网络就可以正常访问cdn.jsdelivr.net 。

您能否运行一下下面的测试命令，并贴一下运行结果（敏感信息可打码），以便诊断网络限制。

```
curl https://myip.ipip.net
dig cdn.jsdelivr.net
mtr --report cdn.jsdelivr.net
mtr --report --tcp --port=443 cdn.jsdelivr.net
curl -vI https://cdn.jsdelivr.net/npm/fflate@0.7.3/umd/index.js
```

更全面的测试可以参考这篇博文：https://blog.bgme.me/posts/how-to-detect-if-a-website-is-blocked-by-gfw/

--------------

如果可以，您能否在无法访问 cdn.jsdelivr.net 的网络环境下跑一下 OONI Probe 测试，即下载并安装 [OONI](https://ooni.org/install/)（Open Observatory of Network Interference），然后选择网站测试，测试 URL 选择 ``https://cdn.jsdelivr.net/npm/fflate@0.7.3/umd/index.js`` 。

这样即可以对访问限制进行全面的测试，更可以为网络限制留取证据。
