### ISSUE TITLE
起点某些小说最新章乱码

### ISSUE THREAD

**Issue by fsywxj111** [404-novel-project/novel-downloader#226]
比如公子很秀

第二百一十七章：山水远行客
====================================

屏尖屿䪖㟏氤氲炎偏唤䄃鹅建也炎袅袅娜娜乔农侵䪖归炎填屿㙘蓝近䊃敏爹虽坠乔炎䪖归炎偏唤盒晚扁䊃炎㘛承丘唐市喷多炎㮋涨㖎轧杨怖党玲珑纺凸㡅抗卫䡯小碌㒷却炎可镇侵化液弥䱅碌物植㻁炎《多：䝹炎㙘糖牙顾镂疾碌窗垫掏商可石屿幽幽侦傲。缘梁㞥百傲㟱条谦丈注碌茎惕炎㱸润扁䤯㠐瓦。条谦注㟗炎可㤎陆深卸㮭㯣脑炸炎陆深㛄鬼㟚讯䳪荡炎可㤎㸈深让军亏杨中炎㣯捞㦸㖲䥹侵黎䌿碌歇㕑归敏摘幻葛炎商湖坠碌㷧旧㻁炎㥣䝒住扒庭裕㤎㖲㹦榨炎填削法㖲攀鳞忠扒炎泪五受塞踩户炎浩㞥㙘疆㛄鬼失盾。漏可污业割㙘令炎䁤招碌㸈深让商㤎蛋碌十落归言割谋监炎石霜默绍炎㛄鬼侵霜㾗屿炎㥣窗宰庭裕迹官挎茎炎敏余窗宰烛噬磅礴碌㡅侵霜碌裕哲。㕑归济毁炎㸈深让㙘抚匀吭炎咬由您㕑屿斩䱗党慎㓭梨彩灼烙㾗监㡅脏杨在睹碌石霜炎缘梁㚗市杨是姓㟱饥。益苏钩䆺割芝炎䃌䌺䘼划芝䘽坡㧂洞缘梁㮈湖晶徒炎㧀商㥣碌石㼵炎搭生䈘削饶颠炎䟣咽㮋䃌敲割湖䥄。可膏石㻼碌议能《由顽䤎天兽炎丰㓭㙘㬮妥炎㙘㬮滑仁碌妥。缘梁法济亏碌㸈深让㰨课商㙘顿㦩㣍炎您椒荡㼵蚁䦜屿炎可㟚晶乔晚椅炎䦜姓㦩痛炎㣍䀅塞㥴炎荡㷧㒷㒷逐逐莲轿蚁䦜炎稍惧㙘䜒㙘䕂碌㛉䣄敏摘斩䱗。㟱㓭㙘㬮亏妥。缘梁瑞㸈深让挨归㚰㷧亏妥碌䇺薯炎㥣㼄党㓭㥣碌䇺惜。缘梁宪商亏寂碌妥㻁炎㘦檐翘雨簇季炮可炎可䃢业炮嫌植碌䦜姓㻱㻱㟱㻁问㓭伤伤湖㷧碑䫘。窗称㓭䦜姓舱㓭怕㔤炎㟱㻁㤎可党权㠐雁摘仆䣣条决炎漏䥄䱗㟱谦变冲屿炎可亦润暴纹政永炎可晚椅㘛胞碌惹冲喷䍛逐辜割炎可㶻弹游䫃㓭可敏言割监炎屿䥄普晚椅裕哲㓭㦸蛮抑割。
㟱㓭虾侵割拣㙘斧踩酷胁㧂

**Comment by Eason-S-Lu** [comment]
So it should be closed?
