### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by huangliangshusheng** [404-novel-project/novel-downloader#240]
1. 可以选择下载格式。现在插件会同时下载 txt 和 epub 两种格式的文件，希望能选择只下载其中一种。
2. 添加自定义抓取。大多数反爬不严格的网站只需要修改一下章节选择器和内容选择器就可以抓取了，可以在设置添加这两个选项由用户自己定制，这样也可以减少作者的工作量。
3. epub 的格式问题。kindle 现在支持推送 epub 格式的书籍，但是用插件生成的书籍一直不能成功推送，这篇[文章](https://bookfere.com/post/973.html) 上说似乎是导航文档的问题，不知道作者能不能修复以下。

最后感谢作者开发这么实用的插件。

**Comment by yingziwu** [comment]
>可以选择下载格式。现在插件会同时下载 txt 和 epub 两种格式的文件，希望能选择只下载其中一种。

这个感觉没有太大必要，毕竟下载之后可以手动删去不需要的格式。

而且更重要是只下载一种格式，也并不会让脚本运行时内存占用变少，没有多大益处。

>添加自定义抓取。大多数反爬不严格的网站只需要修改一下章节选择器和内容选择器就可以抓取了，可以在设置添加这两个选项由用户自己定制，这样也可以减少作者的工作量。

比较简易版的规则，就是你说的只需要修改章节选择器和内容选择器，脚本中已经附带了 [onePage](https://github.com/404-novel-project/novel-downloader/tree/master/src/rules/onePage)、[onePageWithMultiIndexPage](https://github.com/404-novel-project/novel-downloader/tree/master/src/rules/onePageWithMultiIndexPage)、[twoPage](https://github.com/404-novel-project/novel-downloader/tree/master/src/rules/twoPage) 三个简易模版。

只需要复制一下，然后改一改选择器就OK。

![image](https://user-images.githubusercontent.com/22741471/167712280-7655f370-d37e-45cb-9c1e-b1aeb54805ec.png)

> epub 的格式问题。kindle 现在支持推送 epub 格式的书籍，但是用插件生成的书籍一直不能成功推送，这篇[文章](https://bookfere.com/post/973.html) 上说似乎是导航文档的问题，不知道作者能不能修复以下。

使用 EPUBcheker 检查了一下，之前生成的 epub 文件虽然有小问题，但问题不大。
