### ISSUE TITLE
[Bug]: 无法下载次元姬的小说

### ISSUE THREAD

**Issue by CronusLM** [404-novel-project/novel-downloader#241]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [x] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [x] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [ ] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [x] 小说下载器脚本是唯一用户脚本

### 问题描述

下载不了小说
https://send.bgme.bid/download/f7538dc8464d7a02/#5Hjj1Ln7tX4WkgEl3YzHjw
这是脚本失败十次导出的文件

### 问题发生的网址：

https://www.ciyuanji.com/bookDetails/info/5077.html

### 复现步骤

在目录页直接下载不做设置

### 期待的行为

修复下载功能

### 实际的行为

https://send.bgme.bid/download/f7538dc8464d7a02/#5Hjj1Ln7tX4WkgEl3YzHjw

### 小说下载器脚本版本

4.8.4.683 

### 脚本管理器（Tampermonkey/Violentmonkey）版本

4.16

### 浏览器名称及版本

edge 101.0.1210.39

**Comment by yingziwu** [comment]
使用 Firefox、Chromium 进行测试均无法复现

**Comment by CronusLM** [comment]
哪我再用chrome试试吧

**Comment by CronusLM** [comment]
脚本管理器不是唯一插件，我之前看错成唯一脚本管理器，现在只有一个油猴插件的chrome能下载，不知道有什么插件冲突了
