### ISSUE TITLE
部分 Lofter 抓取出错，没有正确识别正文

### ISSUE THREAD

**Issue by yijiluokong** [404-novel-project/novel-downloader#252]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [x] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [x] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [x] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [x] 小说下载器脚本是唯一用户脚本

### 问题描述

在lofter的文章界面和博主的归档界面，脚本既不显示图标，也没有Tampermonkey的脚本控制界面出现，呈现脚本不支持lofter网站的状态

### 问题发生的网址：

https://zhangqilingdeweizhuigu.lofter.com/post/1edf6021_2b5853c1c

### 复现步骤

1. 打开网址
2. 发现脚本的图标没有出现

### 期待的行为

出现脚本图标，脚本正常运行

### 实际的行为

在lofter的文章界面和博主的归档界面，脚本既不显示图标，也没有Tampermonkey的脚本控制界面出现，呈现脚本不支持lofter网站的状态

### 小说下载器脚本版本

4.9.3.721

### 脚本管理器（Tampermonkey/Violentmonkey）版本

4.13.6136

### 浏览器名称及版本

Firefox  91.0 (64 位)

**Comment by yingziwu** [comment]
这个不能算是Bug吧。

因为 Lofter 样式太多，归栏页也不是每个博客都有，所以就将脚本设计为只在 index 页运行。

**Comment by yijiluokong** [comment]
问题解决了，谢谢！

**Comment by yijiluokong** [comment]
脚本在主页下载的文件只有每个文章的标题，没有正文，标题下都是博主的简介。调试日志：https://send.bgme.bid/download/ed1925d52a630c71/#CtlVHra5XVqYhoLhGyYXlA

**Comment by yijiluokong** [comment]
脚本在此网址上仍然存在同样的问题：https://zhangqilingdeweizhuigu.lofter.com/，问题为抓取的文件中每一章的正文都显示为lofter的index页的博主简介。调试日志：https://send.bgme.bid/download/5898910ce6797511/#iODvxz461Y9qB5PnznV--w
