### ISSUE TITLE
[Bug]: 无法抓取海棠的小说

### ISSUE THREAD

**Issue by zsy-caisan** [404-novel-project/novel-downloader#264]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [ ] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [ ] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [ ] 小说下载器脚本是唯一用户脚本

### 问题描述

![S61AU7%@GT29Q44E){UJ@{8](https://user-images.githubusercontent.com/107065311/172436227-b9cb1429-61ea-4c04-84a3-8cc1b2539778.png)
在章节界面，无法自动抓取小说
[novel-downloader-1654619862129.log](https://github.com/404-novel-project/novel-downloader/files/8855036/novel-downloader-1654619862129.log)
。

### 问题发生的网址：

https://www.longmabookcn.com/?act=showinfo&bookwritercode=eb20200913112641441811&bookid=51172&pavilionid=a

### 复现步骤

点进去登录就可以

### 期待的行为

下载小说

### 实际的行为

无法下载

### 小说下载器脚本版本

4.9.3.730

### 脚本管理器（Tampermonkey/Violentmonkey）版本

4.16.1

### 浏览器名称及版本

星愿浏览器

**Comment by yingziwu** [comment]
从日志上看，浏览器内核过老。

请使用最新版 Chrome 或 Fireofx 浏览器。
