### ISSUE TITLE
[Bug]: 晋江小说VIP章节下载有乱码

### ISSUE THREAD

**Issue by cynthialuo01** [404-novel-project/novel-downloader#268]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [x] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [x] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [x] 小说下载器脚本是唯一用户脚本

### 问题描述

点击图标下载后，进度条往前动一点后卡住，按F12查看显示远程字体对照表下载失败
非VIP章节可以正常下载

### 问题发生的网址：

http://www.jjwxc.net/onebook.php?novelid=4296607

### 复现步骤

1.进入晋江网站，登录用户
2.进入想下载的小说页面
3.点击下载图标

### 期待的行为

可以正常下载，没有乱码

### 实际的行为

[debug.log](https://github.com/404-novel-project/novel-downloader/files/8935926/debug.log)

### 小说下载器脚本版本

4.9.3.743

### 脚本管理器（Tampermonkey/Violentmonkey）版本

暴力猴v2.13.0

### 浏览器名称及版本

Firefox  101.0.1 (64 位)

**Comment by yingziwu** [comment]
已修复
https://github.com/404-novel-project/jjwxcFontTables/commit/f208265acef58b389d20094c4af84a2bc90d8d52

**Comment by cynthialuo01** [comment]
谢谢
