### ISSUE TITLE
[Bug]: linovelib部分字乱码

### ISSUE THREAD

**Issue by EinhartStratos** [404-novel-project/novel-downloader#269]
### 问题描述

![image](https://user-images.githubusercontent.com/9413430/174601751-2cbb8b8c-cad8-439f-815f-55608a15508f.png)
![image](https://user-images.githubusercontent.com/9413430/174601782-5877aa53-27bc-4b99-b3a1-bc36f7a557ed.png)

### 问题发生的网址：

https://www.linovelib.com/novel/3209/163881.html

### 小说下载器脚本版本

 4.9.3.743

### 脚本管理器（Tampermonkey/Violentmonkey）版本

暴力猴v2.13.0

### 浏览器名称及版本

Chrome 101.0.4951.54

**Comment by yingziwu** [comment]
哩哔轻小说真不要脸
