### ISSUE TITLE
站点请求：爱尚小说网

### ISSUE THREAD

**Issue by yingziwu** [404-novel-project/novel-downloader#272]
- 站点名称：爱尚小说网
- 站点URL：https://www.23xstxt.com/
- 站点类型：转载网站
- 备注：笔趣阁

https://greasyfork.org/en/scripts/406070-%E5%B0%8F%E8%AF%B4%E4%B8%8B%E8%BD%BD%E5%99%A8/discussions/137546

**Comment by ldm0206** [comment]
https://www.23xsww.cc/
