### ISSUE TITLE
站点请求：轻之国度

### ISSUE THREAD

**Issue by frank3215** [404-novel-project/novel-downloader#277]
- 站点名称：轻之国度
- 站点URL：https://www.lightnovel.us/
- 站点类型：原创（翻译）网站
- 有无收费章节：无。
- 有无如登录墙等额外限制：无需登录即可阅读一些内容，部分内容设置了APP限定，部分内容在APP限定之外还有等级限制。
- 希望添加的理由：轻之国度是一个**有名的**日文轻小说的翻译网站，很多网传的日轻翻译都是出自该网站（**有名**：在我提的转载网站的[站点请求](https://github.com/404-novel-project/novel-downloader/issues/276)中，*很多*值得阅读的书籍都是转载轻之国度的）。问题是，很多轻小说翻译没有释出EPUB下载，且有时图床会[失效](https://www.lightnovel.us/cn/detail/981373)。
- 你认为该站值得阅读的书籍：《[因为女朋友被前辈NTR了，所以我也要NTR前辈的女朋友](https://www.lightnovel.us/cn/series/2159)》（暂无EPUB下载链接，被[哔哩轻小说](https://linovelib.com/novel/3143.html)转载）、《[治癒魔法的錯誤使用法～奔赴戰場的回復要員～ 9](https://www.lightnovel.us/cn/detail/1110052)》、《[与信徒为零的女神大人开始的异世界攻略](https://www.lightnovel.us/cn/series/9)》（从第二卷开始设置了仅限APP访问）、《[年度最垃圾伪圣女(WEB版)](https://www.lightnovel.us/cn/series/254)》（虽然WEB版放出了EPUB下载链接，但[现在还在翻译的](https://www.lightnovel.us/cn/series/1805)文库版还没放出EPUB）、《[不是真正同伴的我被逐出了勇者队伍，于是决定在边境过上慢生活](https://www.lightnovel.us/cn/series/45)》（放出了EPUB下载链接）

注：它形式上比传统的小说网站更偏向于贴吧，释出翻译的方式也更自由：文库版常把一整卷小说放在同一网页中（[例](https://www.lightnovel.us/cn/detail/1110052)）、未把不同卷的轻小说为收到同一合集中、等等。

**Comment by ldm0206** [comment]
目前看来大概的格式是两种：https://www.lightnovel.us/cn/series/2159 类似于小说
https://www.lightnovel.us/cn/detail/1131417 类似于单章
可以暂时按这个设计实现
