### ISSUE TITLE
站点请求：博客来

### ISSUE THREAD

**Issue by DavidQI218** [404-novel-project/novel-downloader#334]
- 站点名称：博客来
- 站点URL：https://www.books.com.tw/
- 站点类型：原创网站 / 转载网站 
- 有无收费章节：有
- 有无如登录墙等额外限制：有
- 希望添加的理由：很多境内不好接触的书
- 你认为该站值得阅读的书籍：百年马拉松 中文版

git上有做下载的插件：https://github.com/lostfilm/books-dl

**Comment by ldm0206** [comment]
已有下载工具
