### ISSUE TITLE
[Bug]: 禁忌书屋的小说，只抓到二层目录，更深层的抓不到

### ISSUE THREAD

**Issue by xibaibai9527** [404-novel-project/novel-downloader#348]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [ ] 我使用的浏览器是最新版 Chrome 或 Firefox
- [ ] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [ ] 小说下载器脚本是唯一用户脚本

### 问题描述

首先感谢开发者作出这么好的扩展程序，下载小说真的是省了大量时间，从繁重的重复性工作中解脱出来，鼠标手救星！

最近下载禁忌书屋的时候，发现有些小说太长，目录里分成了多个楼中楼，但小说下载器只能抓取二级目录，三级目录抓不到。
比如这本《烈火凤凰》：https://www.cool18.com/bbs4/index.php?app=forum&act=threadview&tid=44440
只能抓取到“第四章”，抓取不到“第一节”
![截图01](https://user-images.githubusercontent.com/19858971/194133557-0bf800d3-ac9c-4dc4-b945-cd27d289d37c.png)
下载之后打开txt发现这几章都是空的

其次，同样问题出现在目录页上
比如目录页是这么写的：
![截图02](https://user-images.githubusercontent.com/19858971/194134109-ef74dd81-3fe0-42ce-84bb-581bd36fb453.png)

但是这个“05-08”，点开后的页面只有05，其余三章都在楼中楼
![截图03](https://user-images.githubusercontent.com/19858971/194134229-119b728a-97c5-4b80-8aa2-4f8550e7ce3e.png)

一样，打开txt后发现没有被下载

### 问题发生的网址：

https://www.cool18.com/bbs4/index.php?app=forum&act=threadview&tid=44440

### 复现步骤

1.打开网页
2.点击下载
3.缺失章节

### 期待的行为

期待修复

### 实际的行为

日志没报错

### 小说下载器脚本版本

4.9.4.789

### 脚本管理器（Tampermonkey/Violentmonkey）版本

4.16.1

### 浏览器名称及版本

360chrome

**Comment by ldm0206** [comment]
没办法修，这个目录排版是作者自己编辑的，总不能一本小说一本小说地适配
