### ISSUE TITLE
[Bug]: 晋江文学下载不了了， 打开网页不出现下载图标，望修复

### ISSUE THREAD

**Issue by jeysir** [404-novel-project/novel-downloader#352]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

晋江文学下载不了了， 打开网页不出现下载图标，望修复

### 问题发生的网址：

https://www.jjwxc.net/

### 复现步骤

1.不懂
2.不懂
3.不懂

### 期待的行为

修复晋江文学下载

### 实际的行为

不出现下载按钮

### 小说下载器脚本版本

最新版本

### 脚本管理器（Tampermonkey/Violentmonkey）版本

Violentmonkey

### 浏览器名称及版本

QQ浏览器以及edge

**Comment by quitdoing** [comment]
我也遇到了，然后发现是environment的window加载有问题，把源码4821行的window改为常数，图标就会出现，可以暂且粗暴地解决。

**Comment by jeysir** [comment]
> 我也遇到了，然后发现是environment的window加载有问题，把源码4821行的window改为常数，图标就会出现，可以暂且粗暴地解决。

请问具体怎么修改，是把windows改为“常数”这两个中文？ 还是说输入123456这些数字

**Comment by jeysir** [comment]
> > 我也遇到了，然后发现是environment的window加载有问题，把源码4821行的window改为常数，图标就会出现，可以暂且粗暴地解决。
> 
> 请问具体怎么修改，是把windows改为“常数”这两个中文？ 还是说输入123456这些数字

window: Object.keys(window).length,

还有就是有两个window,是两个都改吗

**Comment by quitdoing** [comment]
把Object.keys(window).length去掉，改成数字，我随便填了个200，保存之后刷新晋江页面应该就能看见。
不过那天我改完发现晋江的问题不止这个，买了的vip章节还是没法下载，获取到的URL是空的，所以还是得等作者修复。😂

**Comment by jeysir** [comment]
> 把Object.keys(window).length去掉，改成数字，我随便填了个200，保存之后刷新晋江页面应该就能看见。 不过那天我改完发现晋江的问题不止这个，买了的vip章节还是没法下载，获取到的URL是空的，所以还是得等作者修复。😂

哦哦，这样啊 ~ 下载不了买了的VIP章节的话那不行呀。还是等作者修复吧。
还是谢谢你的解答

**Comment by cynthialuo01** [comment]
我遇到了同样的问题，求修复
