### ISSUE TITLE
站点请求：ESJ Zone

### ISSUE THREAD

**Issue by blip-glitch** [404-novel-project/novel-downloader#353]
- 站点名称：ESJ Zone
- 站点URL：https://www.esjzone.cc/
- 站点类型：原创网站 / 转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：需登录，需翻墙，且使用韩国日本ip无法访问（https://www.esjzone.cc/forum/1585970655/126053.html ）
- 希望添加的理由：近期大量文库本涉嫌侵权被下架（https://www.esjzone.cc/forum/1585970655/125539.html ），虽然官方有公共账号可浏览（https://www.esjzone.cc/forum/1585970655/132481.html ），但有使用时间限制，希望添加后能本地保存小说且便于在墨水屏设备上阅读
- 你认为该站值得阅读的书籍：普通web日轻：我不是主人公！ 大量r18日轻：萝莉控勇者的凌辱霸道　～侵犯幼女们后魔力增强～ 以及部分原创轻小说和韩国轻小说

**Comment by ldm0206** [comment]
#310
