### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shukekanme** [404-novel-project/novel-downloader#366]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [ ] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

息壤中文网无法下载已经购买的付费章节

### 问题发生的网址：

www.xrzww.com

### 复现步骤

Nothing to preview

### 期待的行为

期待修复

### 实际的行为

正常使用脚本，无法获取已经购买的vip内容

### 小说下载器脚本版本

4.9.4789

### 脚本管理器（Tampermonkey/Violentmonkey）版本

1.0.4

### 浏览器名称及版本

Microsoft Edge

**Comment by selfexplanatory** [comment]
Firefox +1
另外希望加入 xrzww.com 这个网址
