### ISSUE TITLE
站点请求：顶点小说

### ISSUE THREAD

**Issue by hbhxx** [404-novel-project/novel-downloader#369]
- 站点名称：顶点小说
- 站点URL：https://www.ddyueshu.com/
- 站点类型：转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：无
- 希望添加的理由：资源丰富
- 你认为该站值得阅读的书籍：

**Comment by Eason-S-Lu** [comment]
support

**Comment by ldm0206** [comment]
笔趣阁类型的
