### ISSUE TITLE
【希望新功能】自定义爬取间隔 或者 爬取失败后自动增大爬取间隔

### ISSUE THREAD

**Issue by Aliceweizhentian** [404-novel-project/novel-downloader#392]
**存在问题**
网站  https://www.630shu.net/   在爬取小说时会被网站ban掉，可能是因为爬取间隔过快，3~5分钟后又可正常访问

**目标愿景**
自定义爬取间隔 或者 爬取失败后提醒用户并自动尝试增大爬取间隔

**参考建议**
可以供参考的建议。

**补充内容**
其他补充内容。

**Comment by sibuzu** [comment]
這個功能非常必要，很多網站都會因為短時間存取次數太多而停掉，當請優先考慮加入此功能。
