### ISSUE TITLE
[Bug]: 长佩文学下载报错

### ISSUE THREAD

**Issue by yujieweiren** [404-novel-project/novel-downloader#396]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

长佩文学下载报错，下载到第11章就开始报错

### 问题发生的网址：

https://www.gongzicp.com/novel-544165.html

### 复现步骤

1打开网页
2点击下载
3等待报错

### 期待的行为

期待修好能下载

### 实际的行为

[novel-downloader-1672284249001.log](https://github.com/404-novel-project/novel-downloader/files/10317440/novel-downloader-1672284249001.log)

### 小说下载器脚本版本

最新版

### 脚本管理器（Tampermonkey/Violentmonkey）版本

最新版

### 浏览器名称及版本

Microsoft Edge 版本 108.0.1462.54 (正式版本) (64 位)

**Comment by ay2203** [comment]
现在好用了吗？

**Comment by pyrojewelm-art** [comment]
还是不行啊
