### ISSUE TITLE
晋江下载报错

### ISSUE THREAD

**Issue by hshyq** [404-novel-project/novel-downloader#428]
尝试下载的是仅有一章节的小说，点击下载等待几秒后报错，日志见附件
[novel-downloader-1675445854105.log](https://github.com/404-novel-project/novel-downloader/files/10581340/novel-downloader-1675445854105.log)

**Comment by ldm2060** [comment]
单个章节因为没有目录，如要实现抓取就比较麻烦，你可以直接点击插件设置（下载图标右边的齿轮图标），启用测试视图，再在抓取测试页，预览章节序号中输入1，稍等片刻后把抓取到的内容复制了就可以了。
