### ISSUE TITLE
站点请求：腐书宅

### ISSUE THREAD

**Issue by freesialee** [404-novel-project/novel-downloader#43]
- 站点名称：腐书宅
- 站点URL：http://m.fushuzhai.net/
- 站点类型：转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：挂梯时不可浏览
- 希望添加的理由：海棠连载文较全，且在章节浏览页面标题无和谐拼音字

**Comment by yingziwu** [comment]
看了一下，请求目页需要输入验证码。
而且正文页还搞图片外加JS加密（有一点像haitangtxt）。
感觉收益不大，所以就先不添加了。
