### ISSUE TITLE
[Bug]: 起点中文网无法下载，运行时弹窗报错

### ISSUE THREAD

**Issue by wen0513** [404-novel-project/novel-downloader#431]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

点击下载按钮后报“运行过程出错，请至（本网页）反馈问题”
小说无法正常下载

### 问题发生的网址：

https://book.qidian.com/info/1024627913/

### 复现步骤

1.进入网页
2.点击出现的下载按钮
3.脚本报错

### 期待的行为

正常下载

### 实际的行为

[novel-downloader-1675928951533.log](https://github.com/404-novel-project/novel-downloader/files/10694677/novel-downloader-1675928951533.log)
[novel-downloader-1675929027385.log](https://github.com/404-novel-project/novel-downloader/files/10694678/novel-downloader-1675929027385.log)
[novel-downloader-1675929190885.log](https://github.com/404-novel-project/novel-downloader/files/10694679/novel-downloader-1675929190885.log)

### 小说下载器脚本版本

4.9.4.793

### 脚本管理器（Tampermonkey/Violentmonkey）版本

4.18.1

### 浏览器名称及版本

Chrome, 110.0.5481.78 (64位)

**Comment by wen0513** [comment]
报错持续存在
[novel-downloader-1678771675215.log](https://github.com/404-novel-project/novel-downloader/files/10964432/novel-downloader-1678771675215.log)
[novel-downloader-1678771610806.log](https://github.com/404-novel-project/novel-downloader/files/10964433/novel-downloader-1678771610806.log)

**Comment by simonho234** [comment]
我也是
TypeErrorCannot read properties of undefined (reading '_csrfToken')TypeError: Cannot read properties of undefined (reading '_csrfToken')
    at x.bookParse (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=%25E5%25B0%258F%25E8%25AF%25B4%25E4%25B8%258B%25E8%25BD%25BD%25E5%2599%25A8.user.js&id=7369a846-48cb-47cf-aeb1-4d0ed3e73fcf:6534:276629)
    at chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=%25E5%25B0%258F%25E8%25AF%25B4%25E4%25B8%258B%25E8%25BD%25BD%25E5%2599%25A8.user.js&id=7369a846-48cb-47cf-aeb1-4d0ed3e73fcf:6534:479304
    at async chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=%25E5%25B0%258F%25E8%25AF%25B4%25E4%25B8%258B%25E8%25BD%25BD%25E5%2599%25A8.user.js&id=7369a846-48cb-47cf-aeb1-4d0ed3e73fcf:6534:479170[Init]enableDebug: false
[Init]自定义设置：{"enableDebug":false,"chooseSaveOption":"null","enableTestPage":true,"currentTab":"tab-3"}
[run]下载开始
[]
[preTest]nowRunning: 0
TypeErrorCannot read properties of undefined (reading '_csrfToken')TypeError: Cannot read properties of undefined (reading '_csrfToken')
    at x.bookParse (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=%25E5%25B0%258F%25E8%25AF%25B4%25E4%25B8%258B%25E8%25BD%25BD%25E5%2599%25A8.user.js&id=7369a846-48cb-47cf-aeb1-4d0ed3e73fcf:6534:276629)
    at chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=%25E5%25B0%258F%25E8%25AF%25B4%25E4%25B8%258B%25E8%25BD%25BD%25E5%2599%25A8.user.js&id=7369a846-48cb-47cf-aeb1-4d0ed3e73fcf:6534:231585
    at x.run (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=%25E5%25B0%258F%25E8%25AF%25B4%25E4%25B8%258B%25E8%25BD%25BD%25E5%2599%25A8.user.js&id=7369a846-48cb-47cf-aeb1-4d0ed3e73fcf:6534:231710)
    at async chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=%25E5%25B0%258F%25E8%25AF%25B4%25E4%25B8%258B%25E8%25BD%25BD%25E5%2599%25A8.user.js&id=7369a846-48cb-47cf-aeb1-4d0ed3e73fcf:6534:491842运行过程出错，请附上相关日志至支持地址进行反馈。
支持地址：https://github.com/404-novel-project/novel-downloader
