### ISSUE TITLE
[Bug]: 海棠文学城点开没有出现下载的标志

### ISSUE THREAD

**Issue by ruanyqi** [404-novel-project/novel-downloader#434]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [ ] 小说下载器脚本是唯一用户脚本

### 问题描述

打开海棠没有出现下载的标志

### 问题发生的网址：

https://www.longmabookcn.com/?act=managemybookcase

### 复现步骤

点开海棠后找不到下载的标志
重启后还是没有

### 期待的行为

希望能早日弄好，谢谢！

### 实际的行为

点开海棠文学城没办法下载

### 小说下载器脚本版本

4.9.4.789

### 脚本管理器（Tampermonkey/Violentmonkey）版本

最新的

### 浏览器名称及版本

microsoft edge

**Comment by ldm0206** [comment]
海棠域名太多了，插件已经支持了
`
    "*://m.haitangtxt.net/*/*/",
    "*://ebook.longmabook.com/*",
    "*://www.haitangbook.com/*",
    "*://www.longmabookcn.com/*",
    "*://ebook.lmbooks.com/*",
    "*://www.lmebooks.com/*",
    "*://www.haitbook.com/*",
    "*://www.htwhbook.com/*",
    "*://www.myhtebook.com/*",
    "*://www.lovehtbooks.com/*",
    "*://www.myhtebooks.com/*",
    "*://www.myhtlmebook.com/*",
    "*://jp.myhtebook.com/*",
    "*://jp.myhtlmebook.com/*",
    "*://ebook.urhtbooks.com/*",
    "*://www.urhtbooks.com/*",
    "*://www.newhtbook.com/*",
    "*://www.lvhtebook.com/*",
    "*://jp.lvhtebook.com/*",
    "*://www.htlvbooks.com/*",
`
挑一个能打开的用就行
