### ISSUE TITLE
[Bug]: 25中文网（http://www.25zw.org）连续十章下载

### ISSUE THREAD

**Issue by bea452awqqw** [404-novel-project/novel-downloader#448]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

25中文网有下载标志，但下载进程超过一半时突然提示连续十章下载失败

[novel-downloader-1678786319190.log](https://github.com/404-novel-project/novel-downloader/files/10966758/novel-downloader-1678786319190.log)

### 问题发生的网址：

http://www.25zw.org/87804/

### 复现步骤

打开网页 http://www.25zw.org/87804/
点击下载图标
下载开始
中途提示“连续十章下载失败”然后中断下载

### 期待的行为

能够完整下载

### 实际的行为

[novel-downloader-1678786319190.log](https://github.com/404-novel-project/novel-downloader/files/10966800/novel-downloader-1678786319190.log)

### 小说下载器脚本版本

5.1.817

### 脚本管理器（Tampermonkey/Violentmonkey）版本

4.18.1

### 浏览器名称及版本

firefox 浏览器 firefox浏览器版本：110.0.1

**Comment by ldm0206** [comment]
应该是连续下了好几本的缘故，可以等待一段时间再下载另外一本
