### ISSUE TITLE
我得到这个错误。无法下载。

### ISSUE THREAD

**Issue by YuzzuUzzzu** [404-novel-project/novel-downloader#473]
[novel-downloader-1682334975794.log](https://github.com/404-novel-project/novel-downloader/files/11309861/novel-downloader-1682334975794.log)

**Comment by ldm2060** [comment]
插件本身没有问题，重新试试。

**Comment by YuzzuUzzzu** [comment]
谢谢你的答复。下载器的图标在那里。但现在已经不存在了。我关闭和打开了很多次，但仍然无法看到图标。对不起，我在用谷歌翻译。
![Screenshot 2023-04-24 124852](https://user-images.githubusercontent.com/88314967/233987888-f7428676-d768-45a4-a268-1cf3784745d1.png)

**Comment by ldm2060** [comment]
下载器的图标仅出现在小说详情页，形如https://www.gongzicp.com/novel-{num}.html
