### ISSUE TITLE
[Bug]: 下载完成的内容分段混乱

### ISSUE THREAD

**Issue by langZhuYao** [404-novel-project/novel-downloader#474]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

一直在用这个脚本下载小说，之前也从禁忌书屋下载过很多内容，用的都很好，今天发现，下载了两次内容，会出现混乱的分段，就时还是一句完整的句子，然后就分段了，不知道是不是禁忌书屋更新了啥，试过重新安装脚本，也是会出现问题

### 问题发生的网址：

禁忌书屋tid=14328633

### 复现步骤

已经附上tid，因为不是啥正经内容，没有直接贴网址

### 期待的行为

下载分段正确的小说

### 实际的行为

分段混乱无法阅读

### 小说下载器脚本版本

最新版

### 脚本管理器（Tampermonkey/Violentmonkey）版本

Tampermonkey最新版

### 浏览器名称及版本

chrome和edge都试了

**Comment by ldm0206** [comment]
我去查看了该页面，这个换行是作者自己加的
