### ISSUE TITLE
[Bug]: 长佩文学无法下载了

### ISSUE THREAD

**Issue by jeysir** [404-novel-project/novel-downloader#480]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

如题，长佩文学无法下载。
日志一直如下：
[chapter]疑似被阻断，进行随机翻页……
[chapter]随机翻页中……
[chapter]疑似被阻断，进行随机翻页……
[chapter]随机翻页中……
[chapter]随机翻页中……
[chapter]疑似被阻断，进行随机翻页……
[chapter]随机翻页中……
[chapter]随机翻页中……
[chapter]疑似被阻断，进行随机翻页……
[chapter]随机翻页中……
[chapter]随机翻页中……
[chapter]疑似被阻断，进行随机翻页……
[chapter]随机翻页中……
[chapter]随机翻页中……
[chapter]随机翻页中……
[chapter]随机翻页中……

### 问题发生的网址：

https://m.gongzicp.com/novel-692806.html

### 复现步骤

/

### 期待的行为

/

### 实际的行为

/

### 小说下载器脚本版本

最新版本

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.1.825

### 浏览器名称及版本

Edge

**Comment by ldm2060** [comment]
刚才测试了一下，没有问题，仍然可以正常下载，你是不是同时下载了几本了？

**Comment by jeysir** [comment]
没有啊，就下载的一本，难道是我IP限制了？ 但是我也没频繁下载啊，几个月才下一次

**Comment by jeysir** [comment]
> 刚才测试了一下，没有问题，仍然可以正常下载，你是不是同时下载了几本了？

啊，好像又可以了，不知道是不是我之前进的链接是手机版的，规则不一样？
前面我打开的链接是https://m.gongzicp.com/novel-692806.html
现在我直接从电脑端进入长佩首页搜这本小说出来下载，好像没问题了，正在下载。
一会儿要是我没来跟帖的话应该就是成功了

**Comment by ldm2060** [comment]
下载的时候继续阅读长佩的小说也可能会导致此问题，访问次数频率快了就会这样
