### ISSUE TITLE
站点请求：ESJ Zone

### ISSUE THREAD

**Issue by Steven4096** [404-novel-project/novel-downloader#484]
- 站点名称：ESJ Zone
- 站点 URL：https://www.esjzone.cc/或https://esjzone.me/
- 站点类型：原创网站 / 转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：有，需登录，需翻墙，日韩IP无法看轻小说
- 希望添加的理由：丰富的日轻、web文翻译站
- 你认为该站值得阅读的书籍：监禁王

**Comment by ldm2060** [comment]
可以先试试"怠惰小说下载器"，看上去该网站似乎没有额外的防盗措施。

**Comment by Steven4096** [comment]
> 可以先试试“怄惇小说下载器”，看上去该网站似乎几乎没有暴露外部的盗刷施。

那个下载ESJ的小说不好使，只能TXT而且下载不全且章节顺序是乱的

**Comment by ldm0206** [comment]
#353
