### ISSUE TITLE
站点请求：小说狂人

### ISSUE THREAD

**Issue by zhangl81** [404-novel-project/novel-downloader#522]
- 站点名称：小说狂人
- 站点 URL：https://czbooks.net/
- 站点类型：原创网站 / 转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：需要梯子访问
- 希望添加的理由：书很全，更新快，章节内容不会缺胳膊少腿
- 你认为该站值得阅读的书籍：一品丹仙、道祖是克鲁苏等等

**Comment by kuangshenab** [comment]
好人
