### ISSUE TITLE
站点请求：蚂蚁文学

### ISSUE THREAD

**Issue by newbienoobplayer** [404-novel-project/novel-downloader#527]
- 站点名称：蚂蚁文学
- 站点 URL：https://www.mayiwxw.com/
- 站点类型：转载网站
- 有无收费章节：no
- 有无如登录墙等额外限制：no
- 希望添加的理由：书很多
- 你认为该站值得阅读的书籍：这网站随我征战多年，看的书数不胜数 （人话：用习惯了）

**Comment by ldm2060** [comment]
可使用[怠惰小说下载器](https://greasyfork.org/zh-CN/scripts/25068-downloadallcontent)，对于没有下载限制的网站适合此脚本直接下载

**Comment by newbienoobplayer** [comment]
谢谢
