### ISSUE TITLE
站点请求：增加读墨Readmoo 试读版本

### ISSUE THREAD

**Issue by WeeAris** [404-novel-project/novel-downloader#530]
- 站点名称：读墨电子书
- 站点 URL：https://readmoo.com/
- 站点类型：原创网站
- 有无收费章节：有，但试读版本无
- 有无如登录墙等额外限制：有，但试读版本无
- 希望添加的理由：作为低成本的日译中语料，另外有部分试读书籍不支持app试读
- 你认为该站值得阅读的书籍：从小说到专业书籍都有。
- 补充：我自己也解析过，试读版本的网络阅读器和已购版本的网址和nav文件地址都不同，可以用book id直接拼出来，不会和已购版本的下载产生冲突。

**Comment by ldm0206** [comment]
不考虑仅能部分下载的网站，实现了也没人用
