### ISSUE TITLE
站点请求：ESJ

### ISSUE THREAD

**Issue by Loveyat** [404-novel-project/novel-downloader#540]
- 站点名称：ESJ Zone
- 站点 URL：https://www.esjzone.cc/ 或 https://esjzone.me/
- 站点类型：原创网站 +转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：有，需登录，需翻墙，日韩IP无法看轻小说
- 希望添加的理由：内含丰富的日轻、web文翻译站，亦有不少2010年前、早期百度译文
- 你认为该站值得阅读的书籍：侯爵嫡男好色物语

**Comment by ldm0206** [comment]
#353
