### ISSUE TITLE
站点请求：4z6p

### ISSUE THREAD

**Issue by AyanoKiru** [404-novel-project/novel-downloader#544]
- 站点名称：4z6p
- 站点 URL：https://www.4z6p.com
- 站点类型：原创网站
- 有无收费章节：no
- 有无如登录墙等额外限制：no
- 希望添加的理由：no
- 你认为该站值得阅读的书籍：https://www.4z6p.com/book/55989/

**Comment by rockermaexe** [comment]
站点名称：哔哩轻小说
站点 URL：https://moeyy.cn/linovelib/
站点类型：原创网站
有无收费章节：no
有无如登录墙等额外限制：no
希望添加的理由：no
你认为该站值得阅读的书籍：https://linovelib.moeyy.cn/linovelib/novel/3716.html
