### ISSUE TITLE
站点请求：谷歌play读书

### ISSUE THREAD

**Issue by ahihh** [404-novel-project/novel-downloader#549]
- 站点名称：谷歌play读书
- 站点 URL：https://play.google.com/store/books
- 站点类型：原创网站
- 有无收费章节：
- 有无如登录墙等额外限制：有墙
- 希望添加的理由：大多书比其他台湾平台便宜，但是漫画无法直接下载epub
- 你认为该站值得阅读的书籍：

**Comment by yingziwu** [comment]
谷歌play自带下载功能，不在项目考虑范围之内。

**Comment by ahihh** [comment]
https://p.sda1.dev/12/995bcc857e1a738c706e545d426bb45c/4_S@7_5_DB4A__RRAR_2W_2.png
https://p.sda1.dev/12/e87ee378512daf11c48bc5bfd4a72edf/7_`__V`4LCS_9U9KQ@_RL8U.png的确自带下载功能，但是貌似大多数出版商都限制了漫画类的导出功能
https://p.sda1.dev/12/17a08611beeccb0a2b9374e1f0994015/0CTLO9ZJXKY_0O`_P6NFL0C.png 支持设备中如果没标电子阅读器的应该都不支持导出
