### ISSUE TITLE
站点请求：独阅读 免费站

### ISSUE THREAD

**Issue by dianso** [404-novel-project/novel-downloader#550]
- 站点名称：独阅读
- 站点 URL：https://www.duyuedu.net/book/book_detail/100183591
- 站点类型：转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：无
- 希望添加的理由：免费无错
- 你认为该站值得阅读的书籍：

**Comment by dengjichao2005** [comment]
有《奋斗在基辅》免费看的吗

**Comment by ldm0206** [comment]
该网站已经没有在维护
