### ISSUE TITLE
站点请求：腐小说

### ISSUE THREAD

**Issue by IVKylin** [404-novel-project/novel-downloader#564]
- 站点名称：腐小说
- 站点 URL：http://www.fuxs1.com/、http://t1.fuxsw.cc/
- 站点类型：转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：无
- 希望添加的理由：小说较全！
- 你认为该站值得阅读的书籍：非常多

**Comment by ldm0206** [comment]
http://www.fxshu.top/
