### ISSUE TITLE
[Bug]: 晋江文学城远程字体对照表下载失败

### ISSUE THREAD

**Issue by moonaileen** [404-novel-project/novel-downloader#567]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [ ] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

在下载晋江文学城VIP章节时，遇到个别章节的远程字体对照表下载失败，下载下来的文件出现缺字漏字的情况。

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=5082661

### 复现步骤

1.登陆账号
2.已确认购买了本书的VIP章节
3.下载过程中日志显示个别字体对照表下载失败，如：
[jjwxc-font]远程字体对照表 jjwxcfont_3fp6b 下载失败
4.按F12开启检查提示是500错误：服务器超载。
5.尝试别的VIP书籍下载，也会出现同样的错误，但都是不一样的远程字体对照表下载失败。

### 期待的行为

正常下载小说。

### 实际的行为

因为字体对照表下载失败，导致下载下来的文件出现缺字漏字的情况。

### 小说下载器脚本版本

5.2.885

### 脚本管理器（Tampermonkey/Violentmonkey）版本

4.19.0

### 浏览器名称及版本

Edge 117.0.2045.35

**Comment by JoMoney963** [comment]
同样出现该问题。

**Comment by JoMoney963** [comment]
[novel-downloader-1697192460180.log](https://github.com/404-novel-project/novel-downloader/files/12892640/novel-downloader-1697192460180.log)

**Comment by shisantuya** [comment]
出现同样错误，后续章节下载失败
[novel-downloader-1732155777890.log](https://github.com/user-attachments/files/17838945/novel-downloader-1732155777890.log)
