### ISSUE TITLE
[Bug]: 飘天文学无发找到下载按钮

### ISSUE THREAD

**Issue by newbienoobplayer** [404-novel-project/novel-downloader#584]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

如题, 

### 问题发生的网址：

https://www.ptwxz.net/ptkojwo      https://www.ptwxz.net/

### 复现步骤

打开网站,随便找一本书,莫得下载按钮
![image](https://github.com/404-novel-project/novel-downloader/assets/138718840/47e50fe4-694b-49ff-b8da-7af00eabc734)

### 期待的行为

出现类似于右上方的下载按钮

![image](https://github.com/404-novel-project/novel-downloader/assets/138718840/6c42d8ae-2584-4366-8aa5-94a5a2ad2af8)

### 实际的行为

没有出现载按钮

### 小说下载器脚本版本

v5.2.885

### 脚本管理器（Tampermonkey/Violentmonkey）版本

Tampermonkey® by Jan Biniok v4.19.0

### 浏览器名称及版本

Version 116.0.5845.180 (Official Build) (64-bit)

**Comment by newbienoobplayer** [comment]
@kerriajaponica 大佬,请您帮一下

**Comment by kerriajaponica** [comment]
网页结构改了,整不了,等脚本作者修复
我只是路过的,我也不知道这脚本内部原理,不用啥都问我

> @kerriajaponica 大佬,请您帮一下

**Comment by newbienoobplayer** [comment]
好的谢谢，请问这个问题应该问谁？

**Comment by ldm0206** [comment]
脚本支持的飘天文学网域名如下：www.piaotia.com
