### ISSUE TITLE
站点请求：m.bqu9.cc/

### ISSUE THREAD

**Issue by HBL-42** [404-novel-project/novel-downloader#587]
- 站点名称：笔趣阁
- 站点 URL：https://m.bqu9.cc/
- 站点类型：转载网站(盗版？）
- 有无收费章节：无
- 有无如登录墙等额外限制：无
- 希望添加的理由：更新慢几章可防防盗，无广告，较冷门的书也有，无错字，一章分多页
- 你认为该站值得阅读的书籍：

**Comment by ldm0206** [comment]
https://www.bqu9.cc/
