### ISSUE TITLE
站点请求：公众号站点

### ISSUE THREAD

**Issue by uzuki5245** [404-novel-project/novel-downloader#589]
- 站点名称：指尖美书
- 站点 URL：https://zjms.reading.163.com/index.do
- 站点类型：原创网站
- 有无收费章节：有
- 有无如登录墙等额外限制：该站点只能通过wechat内置浏览器打开。
- 并且这似乎是一个分销网站，为163旗下的独立平台小说推广。
- 希望添加的理由：有些小说在163在线网站上找不到，只能在这里看到。
- 既然找不到在外部浏览器打开的方法，请问在微信不支持油猴的情况下，脚本可以通过Devtools等方式导入吗？
- 你认为该站值得阅读的书籍：帮朋友找书，似乎有些老练的小白文

**Comment by ldm0206** [comment]
似乎不仅是限制user agent，而是网站需要用微信平台api认证登录（方便一键充钱？），且连章节页也只能内置打开。
