### ISSUE TITLE
站点请求：

### ISSUE THREAD

**Issue by shisantuya** [404-novel-project/novel-downloader#590]
- 站点名称：镇魂小说网
- 站点 URL：https://www.zhenhunxiaoshuo.com/
- 站点类型：转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：不确定，因为我在墙外
- 希望添加的理由：这里有很多现在看不了（锁了的没了的）的一些“老小说”，如果可以保存成txt版本真的很好。无论是自己再看还是留一份当做存档。
- 你认为该站值得阅读的书籍：看过七爷，天涯客 都是我没保存txt现在找不到了的

**Comment by ldm0206** [comment]
可以使用 https://greasyfork.org/zh-CN/scripts/25068-downloadallcontent 或者 https://github.com/dodying/UserJs/blob/master/novel/novelDownloader/novelDownloader3.user.js 下载
