### ISSUE TITLE
[Bug]: 晋江文学城无法下载vip章节

### ISSUE THREAD

**Issue by yuxx817133** [404-novel-project/novel-downloader#592]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [ ] 我使用的浏览器是最新版 Chrome 或 Firefox
- [ ] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [ ] 小说下载器脚本是唯一用户脚本

### 问题描述

免费章可以下载，vip章节卡住或者下载完是空白章节

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=5275521

### 复现步骤

1.登陆账号
2.已确认购买了本书的VIP章节
3.下载过程卡住，无论等多久进度条仍不加载
4.多次重试仍无法下载
5.尝试别的VIP书籍下载，均出现同样的错误

### 期待的行为

正常下载

### 实际的行为

[Init]ScriptHandler version：4.19.0
[Init]Novel-downloader version：5.2.885
[attachment] https://i9-static.jjwxc.net/novelimage.php?novelid=5275521&coverid=115&ver=693529420023c35f69e3149d395295a4 下载完成。
[Init]enableDebug: false
[Init]自定义设置：{"enableDebug":false,"chooseSaveOption":"null","enableTestPage":true,"currentTab":"tab-1"}
[run]下载开始
[]
[preTest]nowRunning: 0
[fflateZip] filename: [十六春令]穿进男团选秀后.epub, stream: false, streamSaver.supported: true
[initChapters]开始初始化章节
[initChapters] attachmentMode: TM
[initChapters] charset: GB18030
[initChapters] concurrencyLimit: 5
[initChapters] streamZip: false
[initChapters] needLogin: false
[initChapters] nsfw: false
[initChapters] maxRunLimit: undefined
[initChapters] saveOptions: undefined
[initChapters] book: [object Object]
[initChapters] saveType: undefined
[initChapters] bcWorker: [object BroadcastChannel]
[initChapters] bcWorkerMessages: [object Object]
[initChapters] audio: [object HTMLAudioElement]
[Chapter]章节名：第2章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=2, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第5章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=5, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第4章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=4, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第3章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=3, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第1章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=1, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第7章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=7, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第6章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=6, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第9章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=9, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第8章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=8, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第10章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=10, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第11章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=11, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第12章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=12, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第13章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=13, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第14章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=14, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第16章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=16, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第15章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=15, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第17章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=17, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第18章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=18, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第19章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=5275521&chapterid=19, VIP:false, Paid:null, isNull:false 解析成功。

### 小说下载器脚本版本

5.2.885

### 脚本管理器（Tampermonkey/Violentmonkey）版本

4.19.0

### 浏览器名称及版本

Microsoft Edge 版本 116.0.1938.81 (正式版本) (64 位)

**Comment by AkiGoat** [comment]
您试过加这个token了吗？
https://github.com/404-novel-project/novel-downloader#%E6%99%8B%E6%B1%9F%E6%96%87%E5%AD%A6%E5%9F%8E

**Comment by yuxx817133** [comment]
已添加token

**Comment by Sylvene123** [comment]
我差不多一樣的情況，試了很多次，後來VIP章節奇數章節可以下，偶數章節一直都無法下....很奇怪

**Comment by Sylvene123** [comment]
但我後來換成Chrome(原本用Microsoftedge)，novel腳本改成greasyfork版，先下了5章VIP試試看，發現竟然可以了，再一次下全部章節也OK

**Comment by 007MZY0524** [comment]
+1

**Comment by yuxx817133** [comment]
浏览器换成chrome之后就好了

**Comment by yuxx817133** [comment]
浏览器换成chrome之后不卡了，但是很多章节都是空白的

**Comment by Astral3** [comment]
+1

**Comment by lovemysasa777** [comment]
> 但我後來換成Chrome(原本用Microsoftedge)，novel腳本改成greasyfork版，先下了5章VIP試試看，發現竟然可以了，再一次下全部章節也OK

你好我也是chrome，只能下双数章节，不能下单数的。。。请问“novel腳本改成greasyfork版”是指把现有的插件删除，再安装greasyfork版插件、然后安装本脚本吗？

**Comment by Sylvene123** [comment]
> > 但我後來換成Chrome(原本用Microsoftedge)，novel腳本改成greasyfork版，先下了5章VIP試試看，發現竟然可以了，再一次下全部章節也OK
> 
> 你好我也是chrome，只能下双数章节，不能下单数的。。。请问“novel腳本改成greasyfork版”是指把现有的插件删除，再安装greasyfork版插件、然后安装本脚本吗？

對，我記得有幾個可以選的腳本，我把原本的刪掉重新安裝greasyfork版後就可以了

**Comment by Sylvene123** [comment]
> > > > > > 但我後來換成Chrome(原本用Microsoftedge)，novel腳本改成greasyfork版，先下了5章VIP試試看，發現竟然可以了，再一次下全部章節也OK
> > > > > 
> > > > > 
> > > > > 你好我也是chrome，只能下双数章节，不能下单数的。。。请问“novel腳本改成greasyfork版”是指把现有的插件删除，再安装greasyfork版插件、然后安装本脚本吗？
> > > > 
> > > > 
> > > > 對，我記得有幾個可以選的腳本，我把原本的刪掉重新安裝greasyfork版後就可以了
> > > 
> > > 
> > > 感谢回复！不过我试了几次都不行，泪目。。。我连电脑都重启了 T T
> > 
> > 
> > 你是用Tampermonkey嗎？有新增token的腳本？
> 
> 我是小白，不太明白token是啥（我太菜了555

我也是小白，別妄自菲薄。按照這個網站寫的步驟加token腳本。但在這之前你要先去抓token（我是看fiddler抓包教程，搜一下能找到教程）。
