### ISSUE TITLE
站点请求：Penana

### ISSUE THREAD

**Issue by moonaileen** [404-novel-project/novel-downloader#597]
- 站点名称：Penana
- 站点 URL：https://www.penana.com/home.php
- 站点类型：原创网站
- 有无收费章节：有
- 有无如登录墙等额外限制：无
- 希望添加的理由：是台湾的网文聚集地

**Comment by ldm0206** [comment]
fix in https://github.com/404-novel-project/novel-downloader/commit/c2b8f3985f49753a48bbf7314a94fa713ef0078a
