### ISSUE TITLE
[Bug]: 晋江文学城出现“连续十章下载失败，放弃本次下载”

### ISSUE THREAD

**Issue by littlefish92** [404-novel-project/novel-downloader#599]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

晋江文学城下载小说时，出现“连续十章下载失败，放弃本次下载”

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=8205169

### 复现步骤

[novel-downloader-1702219321125.log](https://github.com/404-novel-project/novel-downloader/files/13628145/novel-downloader-1702219321125.log)

### 期待的行为

正常下载小说

### 实际的行为

[novel-downloader-1702219321125.log](https://github.com/404-novel-project/novel-downloader/files/13628146/novel-downloader-1702219321125.log)

### 小说下载器脚本版本

novel-downloader 5.2.885

### 脚本管理器（Tampermonkey/Violentmonkey）版本

Tampermonkey 4.19.0

### 浏览器名称及版本

Microsoft Edge 119.0.2151.97

**Comment by ll0yiya** [comment]
一樣情況，Tampermonkey 4.19.0或5.0，用firefx及chrome都無法下載vip章節，偶爾能下vip 偶數章節，有試過當天限免vup章節，也試過以前買過的章節，都無法正常下載，已設晉江token。

**Comment by Lynn27143** [comment]
一样的问题，显示无法连续下载十章，晋江目录页面无法点开后面十章的内容。一会后可以点开后十章，但下载图标不见了，篡改猴中插件图标变灰了

**Comment by ldm2060** [comment]
设置token后下载试试，默认方式需要等待字体文件更新

**Comment by ll0yiya** [comment]
> 设置token后下载试试，默认方式需要等待字体文件更新

請問token會變嗎？我12/13用安卓晉江與抓包精靈抓出的token是31780195_8662a044894757fc12fb7547e40@@@@@(@為我設的馬賽克)
那幾天也成功抓取章節
這幾天一直失敗，今天我決定再抓一次看看，結果token變了，現在是
31780195_bc4b683a1330af19fe4a4a0cec0@@@@@(@為我設的馬賽克)
終於可以成功抓到。

難道每過幾天，token會變嗎？

**Comment by Lynn27143** [comment]
列位，我完全不会编程语言，并不知道如何设置token，也没有搜到相关晋江的教程，能不能教教我怎么做

**Comment by ll0yiya** [comment]
這是我之前努力寫下的，不知你看不看得懂？

方法：
1) 安裝 暴力猴或篡改猴或油猴
暴力猴 https://www.yxnet.net/479.html
篡改猴 https://www.tampermonkey.net/

2) 裝好上者後，尋找指令碼novel-downloader
https://greasyfork.org/en/scripts/406070-%E5%B0%8F%E8%AF%B4%E4%B8%8B%E8%BD%BD%E5%99%A8  按install
https://github.com/404-novel-project/novel-downloader (這個聽說更新較快，裝法是點code，複製url到匯入那裡安裝，不過我主要是看issues那裡有無人反應不成功的狀況)

裝好要在晉江該篇小說的首頁，以下複製novel-downloader說明：

本指令碼執行下載任務時將播放無聲音訊，以保證指令碼背景執行時不被休眠。
如果本指令碼支援該小說網站，當打開小說目錄頁時，網頁右上角會出現下載圖示，點選該圖示即可開始下載。
如果你要下載的小說章節較多，等待時間可能較長，此時請耐心等待。
你通過右下角進度條瞭解當前下載進度，或者按下 F12，打開網頁控制台查看當前下載狀態。
下載完成後，本指令碼將會自動下載一個 TXT 文件及 EPUB 文件。
TXT 文件請使用記事本或其它閱讀軟體進行閱讀。
EPUB 文件請使用相應閱讀器閱讀。

補充：novel-downloader圖示左邊是下載，
右邊齒輪可以設定，基本設定我會點選第xx章，自訂篩選如果你只要下某幾章就去序號寫如45-87
設定完後記得save，再點圖示左邊的下載。

不過設定到這步，還是下不全，novel-downloader說明：

當前部分網站（如晉江文學城）需要手動填寫登錄 token。
晉江文學城

下載抓包精靈（可在 Google Play、酷安搜尋到，其他軟體也可以）並組態好設定，然後登錄晉江文學城 android app (iOS 平台不適用)並隨意瀏覽章節，在形如「https://app.jjwxc.org/androidapi/chapterContent?」 等連結中找到&token=後的字串（止於下一個&）。

在指令碼管理器中新建如下指令碼（不要把該指令碼程式碼和其他指令碼程式碼合併，除非你完全理解指令碼的意思）並保存：

// ==UserScript==
// [@name](https://www.paipai.fm/u.php?uid=23627)           auto inject tokenOptions
// [@name](https://www.paipai.fm/u.php?uid=23627)  space    http://tampermonkey.net/
// [@version](https://www.paipai.fm/u.php?uid=159887)        0.1
// @description  auto inject tokenOptions
// @author       You
// [@match](https://www.paipai.fm/u.php?uid=561561)          *://*/*
// [@grant](https://www.paipai.fm/u.php?uid=34399)          none
// ==/UserScript==

(function () {
  "use strict";

  const tokenOptions = {
    Jjwxc: "填入token，形如客戶號+下劃線'_'+字母與數字混合的字串",
  };
  window.tokenOptions = tokenOptions;
})();

例如：

    Jjwxc:"11111111_750afc84c839aaaaafccd841fffd11f1",

以上這部份我試了很久，分享如下：
抓包精靈   https://apkpure.com/cn/netcapture/com.minhui.networkcapture

因為我不想在Android手機上試，所以我是在PC上安裝Android模擬器安裝 抓包精靈跟晉江apk
使用方法我參考這2帖  https://blog.csdn.net/weixin_61081791/article/details/126626524
不過後來一直弄不成根證書也達成目的
設定可允許懸浮窗設定， 方便抓包的時候看到是否返回介面資訊  這個我做了，比較方便

我是先開晉江，登入並找一篇限免的書，此時打開抓包精靈(NetCapture)，點右下的start
再回到晉江，此時右邊有個懸浮白點，我點一章翻個幾頁，又到目錄看看
這時再點白點，選text，找內容是像「https://app.jjwxc.org/androidapi/chapterContent?」
按copy搜token,可能有2~3個要點進去查看。找到後複製類似這樣 11111111_750afc84c839aaaaafccd841fffd11f1
_之前的就是你晉江證號，後面就是token
做一次就好了。

之後就到新增指令碼處複製novel-downloader在晉江文學城處寫的指令碼填上token，之後就能下載無缺字的章節了（要已購買或試限免的書）。

感謝某網友教我，我自己又摸索了很久，所以乾脆整理出來跟大家分享。

**Comment by ldm2060** [comment]
> > 设置token后下载试试，默认方式需要等待字体文件更新
> 
> 請問token會變嗎？我12/13用安卓晉江與抓包精靈抓出的token是31780195_8662a044894757fc12fb7547e40@@@@@(@為我設的馬賽克) 那幾天也成功抓取章節 這幾天一直失敗，今天我決定再抓一次看看，結果token變了，現在是 31780195_bc4b683a1330af19fe4a4a0cec0@@@@@(@為我設的馬賽克) 終於可以成功抓到。
> 
> 難道每過幾天，token會變嗎？

一般来说如果你在app上重新登录或者退出，token就需要更新了

**Comment by ll0yiya** [comment]
> > > 设置token后下载试试，默认方式需要等待字体文件更新
> > 
> > 
> > 請問token會變嗎？我12/13用安卓晉江與抓包精靈抓出的token是31780195_8662a044894757fc12fb7547e40@@@@@(@為我設的馬賽克) 那幾天也成功抓取章節 這幾天一直失敗，今天我決定再抓一次看看，結果token變了，現在是 31780195_bc4b683a1330af19fe4a4a0cec0@@@@@(@為我設的馬賽克) 終於可以成功抓到。
> > 難道每過幾天，token會變嗎？
> 
> 一般来说如果你在app上重新登录或者退出，token就需要更新了

原來如此！我的確是幫朋友找token退出又登入，現在就知道了

**Comment by Lynn27143** [comment]
大概看懂步骤了，但我不太想用电脑安装模拟器，这个事不着急，说不定会有更新修复，但依然非常感谢你的攻略！！

**Comment by ll0yiya** [comment]
> 大概看懂步骤了，但我不太想用电脑安装模拟器，这个事不着急，说不定会有更新修复，但依然非常感谢你的攻略！！

你可以直接用安卓手機弄

**Comment by littlefish92** [comment]
> 這是我之前努力寫下的，不知你看不看得懂？
> 
> 方法：
> 
> 1. 安裝 暴力猴或篡改猴或油猴
>    暴力猴 https://www.yxnet.net/479.html
>    篡改猴 https://www.tampermonkey.net/
> 2. 裝好上者後，尋找指令碼novel-downloader
>    https://greasyfork.org/en/scripts/406070-%E5%B0%8F%E8%AF%B4%E4%B8%8B%E8%BD%BD%E5%99%A8  按install
>    https://github.com/404-novel-project/novel-downloader (這個聽說更新較快，裝法是點code，複製url到匯入那裡安裝，不過我主要是看issues那裡有無人反應不成功的狀況)
> 
> 裝好要在晉江該篇小說的首頁，以下複製novel-downloader說明：
> 
> 本指令碼執行下載任務時將播放無聲音訊，以保證指令碼背景執行時不被休眠。 如果本指令碼支援該小說網站，當打開小說目錄頁時，網頁右上角會出現下載圖示，點選該圖示即可開始下載。 如果你要下載的小說章節較多，等待時間可能較長，此時請耐心等待。 你通過右下角進度條瞭解當前下載進度，或者按下 F12，打開網頁控制台查看當前下載狀態。 下載完成後，本指令碼將會自動下載一個 TXT 文件及 EPUB 文件。 TXT 文件請使用記事本或其它閱讀軟體進行閱讀。 EPUB 文件請使用相應閱讀器閱讀。
> 
> 補充：novel-downloader圖示左邊是下載， 右邊齒輪可以設定，基本設定我會點選第xx章，自訂篩選如果你只要下某幾章就去序號寫如45-87 設定完後記得save，再點圖示左邊的下載。
> 
> 不過設定到這步，還是下不全，novel-downloader說明：
> 
> 當前部分網站（如晉江文學城）需要手動填寫登錄 token。 晉江文學城
> 
> 下載抓包精靈（可在 Google Play、酷安搜尋到，其他軟體也可以）並組態好設定，然後登錄晉江文學城 android app (iOS 平台不適用)並隨意瀏覽章節，在形如「[https://app.jjwxc.org/androidapi/chapterContent?」](https://app.jjwxc.org/androidapi/chapterContent?%E3%80%8D) 等連結中找到&token=後的字串（止於下一個&）。
> 
> 在指令碼管理器中新建如下指令碼（不要把該指令碼程式碼和其他指令碼程式碼合併，除非你完全理解指令碼的意思）並保存：
> 
> // ==UserScript== // [@name](https://www.paipai.fm/u.php?uid=23627) auto inject tokenOptions // [@name](https://www.paipai.fm/u.php?uid=23627) space http://tampermonkey.net/ // [@version](https://www.paipai.fm/u.php?uid=159887) 0.1 // @description auto inject tokenOptions // @author You // [@match](https://www.paipai.fm/u.php?uid=561561) _://_/* // [@grant](https://www.paipai.fm/u.php?uid=34399) none // ==/UserScript==
> 
> (function () { "use strict";
> 
> const tokenOptions = { Jjwxc: "填入token，形如客戶號+下劃線'_'+字母與數字混合的字串", }; window.tokenOptions = tokenOptions; })();
> 
> 例如：
> 
> ```
> Jjwxc:"11111111_750afc84c839aaaaafccd841fffd11f1",
> ```
> 
> 以上這部份我試了很久，分享如下： 抓包精靈 https://apkpure.com/cn/netcapture/com.minhui.networkcapture
> 
> 因為我不想在Android手機上試，所以我是在PC上安裝Android模擬器安裝 抓包精靈跟晉江apk 使用方法我參考這2帖 https://blog.csdn.net/weixin_61081791/article/details/126626524 不過後來一直弄不成根證書也達成目的 設定可允許懸浮窗設定， 方便抓包的時候看到是否返回介面資訊 這個我做了，比較方便
> 
> 我是先開晉江，登入並找一篇限免的書，此時打開抓包精靈(NetCapture)，點右下的start 再回到晉江，此時右邊有個懸浮白點，我點一章翻個幾頁，又到目錄看看 這時再點白點，選text，找內容是像「[https://app.jjwxc.org/androidapi/chapterContent?」](https://app.jjwxc.org/androidapi/chapterContent?%E3%80%8D) 按copy搜token,可能有2~3個要點進去查看。找到後複製類似這樣 11111111_750afc84c839aaaaafccd841fffd11f1 _之前的就是你晉江證號，後面就是token 做一次就好了。
> 
> 之後就到新增指令碼處複製novel-downloader在晉江文學城處寫的指令碼填上token，之後就能下載無缺字的章節了（要已購買或試限免的書）。
> 
> 感謝某網友教我，我自己又摸索了很久，所以乾脆整理出來跟大家分享。

我设置好token后，连续十章下载失败的对话框不会弹出了，但是VIP章节（已购买）无法下载了，进度条就一直卡着。

**Comment by yingthuy** [comment]
> 我设置好token后，连续十章下载失败的对话框不会弹出了，但是VIP章节（已购买）无法下载了，进度条就一直卡着。

我和你一样，购买的VIP程序无法下载，进度条被冻结

**Comment by Seriozhaherx** [comment]
你好，我也是显示连续下载十章失败，自动取消下载，然后我的设备全部都是iOS的设备，也没有任何编程底子，想问问列位解决了这个问题了吗？目前最多只能下载前四十章，之后都下载不了，想问问大家有没有解决方法，真的非常需要了，谢谢
![Uploading 截屏2024-03-02 下午9.44.57.png…]()

**Comment by ll0yiya** [comment]
剛嘗試下整本的確不成功。

**Comment by ll0yiya** [comment]
剛試晉江今日限免：[清和未暑]清冷世子追妻日常（重生）
光下番外正常，下全本30章以後空白。

**Comment by lovemysasa777** [comment]
你好，我是谷歌浏览器PC端，已购买的VIP章节中，可以成功抓取所有“双数章节“（例如第88章、第100章）；但无法抓取所有”单数章节“（如第33章、35章、37章等等），抓取测试显示”章节加载失败！“

**Comment by lovemysasa777** [comment]
> 你好，我是谷歌浏览器PC端，已购买的VIP章节中，可以成功抓取所有“双数章节“（例如第88章、第100章）；但无法抓取所有”单数章节“（如第33章、35章、37章等等），抓取测试显示”章节加载失败！“

感天动地，我按照教程加装了token成功抓取到章节了

**Comment by JoMoney963** [comment]
我现在用抓取精灵抓取不到「[https://app.jjwxc.org/androidapi/chapterContent?」链接咋整啊。
