### ISSUE TITLE
[Bug]: UU看书无法下载小说了

### ISSUE THREAD

**Issue by halo0921** [404-novel-project/novel-downloader#600]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

- 站点名称：UU看书
- 站点 URL：https://www.uukanshu.net/#gsc.tab=0
- 站点类型：转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：无

UU看书无法下载小说，之前还能现在找不到脚本小说下载的按钮。UU看书的网站有几个，每个都尝试过找不到下载按钮。

### 问题发生的网址：

https://www.uukanshu.net/#gsc.tab=0

### 复现步骤

打开网站,随便找一本书,没有下载按钮

### 期待的行为

可以再次在此网站下载小说，右上角能出现按钮下载

### 实际的行为

原本此网站能通过脚本下载小说，现在找不到下载的按钮了

### 小说下载器脚本版本

5.2.885

### 脚本管理器（Tampermonkey/Violentmonkey）版本

Tampermonkey 5.0.0

### 浏览器名称及版本

Chrome 119.0.6045.199和firefox 116.0.3

**Comment by ldm0206** [comment]
现在是不是这个域名：uukanshu.cc

**Comment by ldm0206** [comment]
我搜到的几个都不是UU看书的网站，这个网站应该已经没了，剩下的可以直接用https://greasyfork.org/scripts/25068下载
