### ISSUE TITLE
站点请求：轻之国度

### ISSUE THREAD

**Issue by ying-ck** [404-novel-project/novel-downloader#601]
- 站点名称：轻之国度
- 站点 URL：新：https://www.lightnovel.us/  旧：https://obsolete.lightnovel.us/
- 站点类型：转载网站
- 有无收费章节：无
- 有无如登录墙等额外限制：无法在未登录的情况下查看分类，但小说仍可看。
- 希望添加的理由：书多、免费

**Comment by ldm0206** [comment]
这网站是个论坛？好像没有目录的？

**Comment by ldm0206** [comment]
#277
