### ISSUE TITLE
[Feature Requset]

### ISSUE THREAD

**Issue by Material3600** [404-novel-project/novel-downloader#602]
**存在问题**
因为爬的速度过快，目前脚本在运行时可能会被ban

**目标愿景**
希望能够自定义下载速度，如每秒1章

**参考建议**
无

**补充内容**
无

**Comment by ldm0206** [comment]
这个目前是由代码控制的，可以提供一下是哪些网站有这个防爬的措施

**Comment by Material3600** [comment]
> 这个目前是由代码控制的，可以提供一下是哪些网站有这个防爬的措施

我是在真白萌和哔哩轻小说上遇到，后者现在已经完全不能用这个脚本了

**Comment by ldm0206** [comment]
> > 这个目前是由代码控制的，可以提供一下是哪些网站有这个防爬的措施
> 
> 我是在真白萌和哔哩轻小说上遇到，后者现在已经完全不能用这个脚本了

真白萌应该已经修复了，哔哩轻小说我待会儿看看，是这个链接对吧www.linovelib.com

**Comment by Material3600** [comment]
非常感谢

**Comment by Material3600** [comment]
> > > 这个目前是由代码控制的，可以提供一下是哪些网站有这个防爬的措施
> > 
> > 
> > 我是在真白萌和哔哩轻小说上遇到，后者现在已经完全不能用这个脚本了
> 
> 真白萌应该已经修复了，哔哩轻小说我待会儿看看，是这个链接对吧www.linovelib.com

是的，非常感谢

**Comment by ldm0206** [comment]
> > > > 这个目前是由代码控制的，可以提供一下是哪些网站有这个防爬的措施
> > > 
> > > 
> > > 我是在真白萌和哔哩轻小说上遇到，后者现在已经完全不能用这个脚本了
> > 
> > 
> > 真白萌应该已经修复了，哔哩轻小说我待会儿看看，是这个链接对吧www.linovelib.com
> 
> 是的，非常感谢

哔哩轻小说已经修复，就是不知道为什么原来的代码里有一个“基于邻近章节修复隐藏链接的章节”的部分，请求频繁的报错也与他有关。现在加了延迟后，生成目录的时间会变慢。

如果你要在设置里启用测试试图看抓取测试的话，需要先看看自定义筛选条件里目录是不是生成完了，时间的话我找的那本https://www.bilinovel.com/novel/2139.html大概要1~2分钟的样子，再短的话还是会报错。

有空的话谁可以测一下看看到底需不需要“基于邻近章节修复隐藏链接的章节”，不需要删了话目录解析就是瞬时完成的。
