### ISSUE TITLE
[Bug]: 所有网站都无法显示下载按钮

### ISSUE THREAD

**Issue by chico617** [404-novel-project/novel-downloader#611]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

无法显示悬浮窗 确认网址是支持的网站
<img width="959" alt="{43E10AD4-B997-4df8-9806-D9D3A5865378}" src="https://github.com/404-novel-project/novel-downloader/assets/157688002/398baf68-f36f-4bb2-8cfd-f5a4fcc7ec8d">

### 问题发生的网址：

https://sosad.fun/threads/115157/profile

### 复现步骤

前一天还可以正常使用

### 期待的行为

回复下载按钮

### 实际的行为

下载按钮消失

### 小说下载器脚本版本

	5.2.885

### 脚本管理器（Tampermonkey/Violentmonkey）版本

篡改猴5.0

### 浏览器名称及版本

火狐最新

**Comment by zhaoxishm** [comment]
不要头铁到一定要用火狐啊

**Comment by ldm0206** [comment]
无法复现
