### ISSUE TITLE
[Bug]: 晋江文学城下载失败

### ISSUE THREAD

**Issue by ovowII** [404-novel-project/novel-downloader#614]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [x] 小说下载器脚本是唯一用户脚本

### 问题描述

昨天一切正常，但今天突然无法下载VIP章节（已购买）。 当我按下下载按钮时，下载栏没有显示。

接下来，我关闭了[Auto inject token option]，这次它确实下载了文本，则所有奇数章节（25、27、29等）都是空白的。

如果下载量很大，则会出现此通知（下附图片）
[novel-downloader-1708463225481.log](https://github.com/404-novel-project/novel-downloader/files/14351327/novel-downloader-1708463225481.log)

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=7827348

### 复现步骤

[novel-downloader-1708463225481.log](https://github.com/404-novel-project/novel-downloader/files/14351344/novel-downloader-1708463225481.log)

### 期待的行为

所有章节都可以正常下载。

### 实际的行为

仅下载偶数章节

### 小说下载器脚本版本

5.2.886

### 脚本管理器（Tampermonkey/Violentmonkey）版本

Tampermonkey

### 浏览器名称及版本

Google Chrome- version 121.0.6167.184

**Comment by ovowII** [comment]
我只是想补充一下：在jjwxc的另一本小说中（下面的链接），缺少的是偶数章节。 所以我想，每部小说都有所不同

https://www.jjwxc.net/onebook.php?novelid=7774469

**Comment by ll0yiya** [comment]
我去測試，也是不會下載已購vip章節。

**Comment by xSenbei** [comment]
同样出现该问题。

**Comment by lytieumy** [comment]
同样出现该问题

**Comment by ll0yiya** [comment]
16小時前更新後，已正常，超級感謝！
