### ISSUE TITLE
[Bug]: 晋江收费章节无法下载，部分下载偶数章节

### ISSUE THREAD

**Issue by naitang12398** [404-novel-project/novel-downloader#619]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

晋江收费章节无法下载，部分下载偶数章节，有段时间可以用，然后突然就不可以用了
看不懂token之类的东西

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=8029100

### 复现步骤

[novel-downloader-1709807023372.log](https://github.com/404-novel-project/novel-downloader/files/14522821/novel-downloader-1709807023372.log)

### 期待的行为

可以正常使用，下载收费章节

### 实际的行为

[novel-downloader-1709807023372.log](https://github.com/404-novel-project/novel-downloader/files/14522702/novel-downloader-1709807023372.log)

### 小说下载器脚本版本

更新至最新。不知道多少版本

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.0.1

### 浏览器名称及版本

Firefox 116.0.3.8627

**Comment by XIN817** [comment]
我是只下载奇数章节
