### ISSUE TITLE
[Feature Requset]插件请求网站下载权限

### ISSUE THREAD

**Issue by 502y** [404-novel-project/novel-downloader#622]
**存在问题**
Edge浏览器会自动拦截来自插件的下载请求导致下载伪失败。在插件提示“连续十章无法下载任务自动停止”后，浏览器才会弹出提示询问是否允许网站下载多个文件，这时点击允许会正确下载txt与epub格式文件。同一站点再次尝试下载（浏览器已允许下载），即可正常使用。

**目标愿景**
下载前提示用户允许浏览器下载文件。

**参考建议**
无

**补充内容**
[novel-downloader-1710475437930.log](https://github.com/404-novel-project/novel-downloader/files/14610642/novel-downloader-1710475437930.log)

**Comment by ldm0206** [comment]
应该不是你说的这个问题，解析的时候不会发送下载请求的。飘天有人修复了，等他提交PR后你再试试吧
