### ISSUE TITLE
[Bug]: 移动端Safari中海棠文学城下载完毕后报错。

### ISSUE THREAD

**Issue by XyX203** [404-novel-project/novel-downloader#631]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [ ] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [ ] 小说下载器脚本是唯一用户脚本

### 问题描述

下载完毕后，出现提示“运行过程出错，请附上相关日志至支持......”

### 问题发生的网址：

https://www.haitbook.com/?act=showinfo&bookwritercode=EB20180902195925798885&bookid=21599&pavilionid=a

### 复现步骤

1、打开小说目录
2、点击下载按钮
3、下载过程结束后提示“运行过程出错......”

### 期待的行为

能够得到疑惑解决，谢谢！

### 实际的行为

[novel-downloader-1712933648933.log](https://github.com/404-novel-project/novel-downloader/files/14960404/novel-downloader-1712933648933.log)

### 小说下载器脚本版本

5.2.916

### 脚本管理器（Tampermonkey/Violentmonkey）版本

最新版

### 浏览器名称及版本

Safari17.3.1

**Comment by ldm0206** [comment]
日志里显示保存txt文件时发生了不可读入的错误，可能是浏览器不支持，也可能是网站设置问题，你可以多试几次，以及确保网站有下载文件的权限，如果还不行，那就是确实不支持这个浏览器。
