### ISSUE TITLE
[Bug]: 晋江填写taken下载文档后几天疑似被列入黑名单

### ISSUE THREAD

**Issue by bamboollz** [404-novel-project/novel-downloader#634]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

前几日因下载文档会跳双数或者单数，总有章节下不下来
于是尝试了一下添加了taken，之后下载很顺利
昨日再次下载时发现之前的taken失效，无法下载文档，获取了新taken后可以下载，但是所有已购买的V章均为乱码
接着用不同的手机APP登录晋江发现问题依旧
于是另外注册了一个新号，买了刚刚旧号打开显示不正常的V文，发现一切正常
旧号疑似被晋江列入黑名单，可登录可买问，就是打开所有的V文都显示不正常
不知道是永久还是暂时，尝试过修改密码，问题依旧，如果有最新情况会跟进

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=4398357

### 复现步骤

登录晋江，点开V文，发现显示不正常
退出晋江，建立信号，购买V文，显示正常

### 期待的行为

是否可以不用提供taken也能正常下载已购买文章

### 实际的行为

![8)J)~OLG{G7)8OX2EJ5)B0H](https://github.com/404-novel-project/novel-downloader/assets/135499749/b377584d-8371-4d82-8273-eb690a5b7915)
![1SO4T _FNK3CDRS7`NXM24S](https://github.com/404-novel-project/novel-downloader/assets/135499749/5bb371b4-2e07-45e2-b5ae-405efb80d979)

### 小说下载器脚本版本

5.2.916

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.1.0

### 浏览器名称及版本

Google Chrome 版本 124.0.6367.61（正式版本）

**Comment by moondeity** [comment]
最近晉江不知道系統在更新什麼,其實晉江官方論壇上一直都有人通報這個問題
請聯絡晉江客服修理

**Comment by bamboollz** [comment]
> 最近晉江不知道系統在更新什麼,其實晉江官方論壇上一直都有人通報這個問題 請聯絡晉江客服修理

收到，已打电话过去，客服说帮我上报反馈，不是因为插件问题就最好了，我继续跟进

**Comment by bamboollz** [comment]
已在晋江论坛联系客服成功修复，所有V章回复正常
不过在晋江论坛看到一条“想到之前冰心说过要用的那个新方法，碧水有个帖子提的，不封号，但是会给他一些有问题的内容”这样的评论，不知道最近这种情况是不是在试水
