### ISSUE TITLE
[Bug]: 晋江文学城，付费V章单数章节无法下载，47章后的全部章节下载失败

### ISSUE THREAD

**Issue by Pentasz** [404-novel-project/novel-downloader#635]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

在晋江文学城下载一本已“全文订阅”的小说，付费v章只能下载偶数章，而且从47章后无论奇偶章节都下载失败，显示连续十章下载失败，相关日志如下
[novel-downloader-1716351801314.log](https://github.com/404-novel-project/novel-downloader/files/15398013/novel-downloader-1716351801314.log)

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=3149286

### 复现步骤

如指引操作

### 期待的行为

能正常下载已付费的v章

### 实际的行为

[Uploading novel-downloader-1716351801314.log…]()

### 小说下载器脚本版本

5.2.916

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.1.1

### 浏览器名称及版本

Chrome 已是最新版本 125.0.6422.77

**Comment by sherow** [comment]
同卡进度下载失败

**Comment by gggggenius** [comment]
现在还是没有办法下载47以后的章节
