### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by aaaaaaahaha** [404-novel-project/novel-downloader#637]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

pixiv下载后是乱码

### 问题发生的网址：

https://www.pixiv.net/novel/show.php?id=22128237

### 复现步骤

点击小说下载，下载完后字变成乱码数

### 期待的行为

赶快修复

### 实际的行为

修复好

### 小说下载器脚本版本

5.2.916

### 脚本管理器（Tampermonkey/Violentmonkey）版本

2.19.0

### 浏览器名称及版本

firefox121.0.1

**Comment by ldm0206** [comment]
无法复现
