### ISSUE TITLE
[Bug]: 晋江文学城下载失败

### ISSUE THREAD

**Issue by EICr** [404-novel-project/novel-downloader#640]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [ ] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

下载到小说第48章左右突然报错说连续十章无法解析。所有v章均已购买。
p.s. 由于不打算更新macOS版本所以浏览器并非最新。

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=4336752

### 复现步骤

1. 以购买过此小说的账号进入
2. 点击插件的下载按钮

### 期待的行为

能够成功下载整本小说（付费章节已全部购买）

### 实际的行为

下载到中途报错停止，通知显示“连续十章无法解析”
[novel-downloader-1719142804116.log](https://github.com/user-attachments/files/15944397/novel-downloader-1719142804116.log)

### 小说下载器脚本版本

5.2.916

### 脚本管理器（Tampermonkey/Violentmonkey）版本

Greasemonkey 4.12.0

### 浏览器名称及版本

Firefox 115.7.0esr

**Comment by cynthialuo01** [comment]
我也遇到了同样的问题

**Comment by cynthialuo01** [comment]
[novel-downloader-1719219172643.log](https://github.com/user-attachments/files/15952410/novel-downloader-1719219172643.log)
[novel-downloader-1719219038983.log](https://github.com/user-attachments/files/15952414/novel-downloader-1719219038983.log)

**Comment by LilyliL-YwY** [comment]
同...我也在下载时遇到了同样的报错

**Comment by kikikafka** [comment]
我也在遇到了同样的报错
