### ISSUE TITLE
[Bug]: 长佩文学网无法下载

### ISSUE THREAD

**Issue by boom123557** [404-novel-project/novel-downloader#641]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

点击下载按钮之后显示运行过程出错，请附上相关日志至支持地址进行反馈。

### 问题发生的网址：

https://m.gongzicp.com/novel-844765.html

### 复现步骤

点击下载按钮之后显示运行过程出错，请附上相关日志至支持地址进行反馈。

### 期待的行为

能够继续下载

### 实际的行为

[Init]开始载入小说下载器……
[Init]当前时间：2024-06-27T06:28:18.222Z
[Init]当前页URL：https://m.gongzicp.com/novel-844765.html
[Init]workerId：b6235337-d4ef-4f12-bbcd-d248eaba9b1f
[Init]当前页Referrer：https://www.bing.com/
[Init]浏览器UA：paipai.houdao.forever
[Init]浏览器语言：zh-CN,en,en-GB,en-US,ja
[Init]设备运行平台：
[Init]设备内存：8
[Init]CPU核心数：16
[Init]eval：true, 33
[Init]fetch：true, 29
[Init]XMLHttpRequest：true, 43
[Init]streamSupport：true
[Init]window：244
[Init]localStorage：true
[Init]sessionStorage：true
[Init]Cookie：true
[Init]doNotTrack：0
[Init]enableDebug：false
[Init]ScriptHandler：Tampermonkey
[Init]ScriptHandler version：5.1.1
[Init]Novel-downloader version：5.2.916
[run]下载开始
[]
[preTest]nowRunning: 0
TypeErrorCannot read properties of null (reading 'innerText')TypeError: Cannot read properties of null (reading 'innerText')
    at h.bookParse (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=%25E5%25B0%258F%25E8%25AF%25B4%25E4%25B8%258B%25E8%25BD%25BD%25E5%2599%25A8.user.js&id=a1ab513c-d67e-4e47-8a61-f5ace83c8fc0:6551:474177)
    at chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=%25E5%25B0%258F%25E8%25AF%25B4%25E4%25B8%258B%25E8%25BD%25BD%25E5%2599%25A8.user.js&id=a1ab513c-d67e-4e47-8a61-f5ace83c8fc0:6551:260123
    at h.run (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=%25E5%25B0%258F%25E8%25AF%25B4%25E4%25B8%258B%25E8%25BD%25BD%25E5%2599%25A8.user.js&id=a1ab513c-d67e-4e47-8a61-f5ace83c8fc0:6551:260248)
    at async chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=%25E5%25B0%258F%25E8%25AF%25B4%25E4%25B8%258B%25E8%25BD%25BD%25E5%2599%25A8.user.js&id=a1ab513c-d67e-4e47-8a61-f5ace83c8fc0:6551:686442运行过程出错，请附上相关日志至支持地址进行反馈。
支持地址：https://github.com/404-novel-project/novel-downloader

### 小说下载器脚本版本

5.2.916

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.2.0

### 浏览器名称及版本

Microsoft edge

**Comment by d5842** [comment]
[novel-downloader-1720092310185.log](https://github.com/user-attachments/files/16097919/novel-downloader-1720092310185.log)

**Comment by youzhazhiliao** [comment]
[novel-downloader-1720614378575.log](https://github.com/user-attachments/files/16161784/novel-downloader-1720614378575.log)

**Comment by Starry25th** [comment]
[novel-downloader-1721529434696.log](https://github.com/user-attachments/files/16322892/novel-downloader-1721529434696.log)

**Comment by HyggeHazel** [comment]
一样的问题，请问有什么解决办法

**Comment by zly0000** [comment]
求求大佬们 这个到底怎么解决啊

**Comment by felthand** [comment]
我也有这个问题
[novel-downloader-1725216125854.log](https://github.com/user-attachments/files/16830148/novel-downloader-1725216125854.log)

**Comment by M-seas** [comment]
遇到相同问题
[novel-downloader-1725962982808.log](https://github.com/user-attachments/files/16943274/novel-downloader-1725962982808.log)

**Comment by HyggeHazel** [comment]
作者在上面回复了修复方法，需要把这里的代码改一下：
![屏幕截图 2024-09-19 094743](https://github.com/user-attachments/assets/d3753e99-ec8a-4812-a614-414ece3699a6)
↑
![屏幕截图 2024-09-19 094607](https://github.com/user-attachments/assets/80d008cd-16c9-4c64-bdba-b0b83ce45fa9)
把[id]换成[c-light-gray]就可以了，亲测有效

**Comment by M-seas** [comment]
> 作者在上面回复了修复方法，需要把这里的代码改一下： ![屏幕截图 2024-09-19 094743](https://private-user-images.githubusercontent.com/169568845/368812908-d3753e99-ec8a-4812-a614-414ece3699a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTMxOTEsIm5iZiI6MTcyNjcxMjg5MSwicGF0aCI6Ii8xNjk1Njg4NDUvMzY4ODEyOTA4LWQzNzUzZTk5LWVjOGEtNDgxMi1hNjE0LTQxNGVjZTM2OTlhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMjI4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDZiNDhmODE1N2YzMGM1MDc4YWRmNGUxNjEyMWUwYTQ1YjM5NjQ2OGZhNDM1YmYyYjBjMzdhNTVlMjg2ZTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.biGyPRzIVCzwoUnLc548tQhQUueADs38UHDjY1HoT3g) ↑ ![屏幕截图 2024-09-19 094607](https://private-user-images.githubusercontent.com/169568845/368813185-80d008cd-16c9-4c64-bdba-b0b83ce45fa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTMxOTEsIm5iZiI6MTcyNjcxMjg5MSwicGF0aCI6Ii8xNjk1Njg4NDUvMzY4ODEzMTg1LTgwZDAwOGNkLTE2YzktNGM2NC1iZGJhLWIwYjgzY2U0NWZhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMjI4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmUzOTIwZmZkNGZmNzA5Y2ZlMmM0ZWMyODJlMDIxNTZmM2NhMWE5OGVkYjJjZGU4NmI5Y2FhYWJjZmRmM2ZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QUOqI2yHCls1EQfWrGDWeCvNLfrf48OXWiqxvh0gPt4) 把[id]换成[c-light-gray]就可以了，亲测有效

感谢！
