### ISSUE TITLE
[Bug]: 晋江输入tocken后解析成功,但下载无内容

### ISSUE THREAD

**Issue by jiaxin0816** [404-novel-project/novel-downloader#647]
### 必要条件

- [x] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

未输入tocken时,可以下载偶数章节,输入tocken后,所有章节无内容,debug文件显示解析成功.

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=8301066

### 复现步骤

[debug.log](https://github.com/user-attachments/files/16322899/debug.log)
[[温水煮书]幼崽教祖爆改世界.txt](https://github.com/user-attachments/files/16322901/default.txt)

### 期待的行为

可以正常下载

### 实际的行为

已购买全部章节,debug解析成功但下载内容为空白

### 小说下载器脚本版本

5.2.916

### 脚本管理器（Tampermonkey/Violentmonkey）版本

Tampermonkey 5.2.2

### 浏览器名称及版本

Googlle

**Comment by ll0yiya** [comment]
我的情況也一樣。

附上我的debug log
[debug.log](https://github.com/user-attachments/files/16324478/debug.log)

**Comment by ovowII** [comment]
ldm0206 创建了解决方案。它是 [Pull Requests] 中的最新帖子。我希望管理员尽快批准合并，这样我们就可以再次下载小说了。
