### ISSUE TITLE
[Bug]: 息壤网站和有毒网站，抓取页面提示：当前app版本过低,请升级后再进行阅读

### ISSUE THREAD

**Issue by subwaygogogo** [404-novel-project/novel-downloader#648]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [ ] 我使用的浏览器是最新版 Chrome 或 Firefox
- [ ] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [ ] 小说下载器脚本是唯一用户脚本

### 问题描述

息壤网站和有毒网站，抓取页面提示：当前app版本过低,请升级后再进行阅读

### 问题发生的网址：

https://www.xrzww.com/bookdetail/103835

### 复现步骤

1 点击下载按钮
2 等待txt生成
3 正文只有“app版本过低”的提示，没有小说正文。

### 期待的行为

正常下载正文

### 实际的行为

出现APP版本过低提示，抓取的TXT只有章节目录，没有正文

### 小说下载器脚本版本

5.2.916

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.1.1

### 浏览器名称及版本

edge

**Comment by subwaygogogo** [comment]
![企业微信截图_20240730174423](https://github.com/user-attachments/assets/f08d8948-5351-47cc-b82a-d92e29f9b0ac)

**Comment by MaggieAnan** [comment]
我也是

**Comment by SWZ128** [comment]
我也遇到了同样的问题

**Comment by buding9527** [comment]
我也遇到了同样的问题
