### ISSUE TITLE
請問高階使用技巧的自訂保存參數？按完F12後要做什麼？

### ISSUE THREAD

**Issue by ll0yiya** [404-novel-project/novel-downloader#650]
我習慣「txt 文件每個自然段前加兩個空格」，可是在設置那裡的「将章节名称格式修改为 第xx章 xxxx」也很重要，可是這2個只能選一個。

在novel-downloader 的高階使用技巧那裡，有個自訂篩選函數：如欲只下載部分章節，請在點選運行按鈕前，按下 F12 打開開發者工具，在 window 下建立 saveOptions 對象等等，我的要求在自訂保存參數

我按了F12後，得到下圖：
![003](https://github.com/user-attachments/assets/bd9e1094-a45e-449d-95c0-07c666760a46)
請問是如附圖的左側按+號，建立 saveOptions 對象，把「txt 文件每個自然段前加兩個空格」以下的碼const saveOptions = {
  genChapterText: (chapterName, contentText) => {那一堆全部貼到右邊嗎？這樣做過一次後是否就永久空2格？

感謝回覆！

**Comment by ldm0206** [comment]
点击主控台，输入 
```javascript
window.saveOptions = {
  genChapterText: (chapterName, contentText) => {
      contentText = contentText
        .split("\n")
        .map((line) => {
          if (line.trim() === "") {
            return line;
          } else {
            return line.replace(/^/, "    ");
          }
        })
        .join("\n");
      return `## ${chapterName}\n\n${contentText}\n\n`;
    },
    getchapterName: (chapter) => {
      if (chapter.chapterName) {
        return `第${chapter.chapterNumber.toString()}章 ${chapter.chapterName}`;
      } else {
        return `第${chapter.chapterNumber.toString()}章`;
      }
    },
  };

```
