### ISSUE TITLE
[Bug]: 只能下载了每隔一章，而不是整个列表

### ISSUE THREAD

**Issue by SylviaLe** [404-novel-project/novel-downloader#652]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

我买了第120章到底145章，可是txt只有番外1，番外3，番外5，等等。或说，每个一张

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=8457883

### 复现步骤

1，登入jjwxc，到https://www.jjwxc.net/onebook.php?novelid=8457883，买所有番外
2，点击下载按钮，等下载完成
3,  打开txt

### 期待的行为

可以看到我已买了所有的章节

### 实际的行为

只看到每隔一章

### 小说下载器脚本版本

5.2.917

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.2.3

### 浏览器名称及版本

Chrome - 128.0.6613.113

**Comment by Uzunami** [comment]
我目前已经一章都下不了、免费和买下来的章节都下不了

**Comment by Uzunami** [comment]
https://github.com/404-novel-project/novel-downloader/issues/644#issuecomment-2268886502

用这个解决了

**Comment by higokei** [comment]
> [#644 (comment)](https://github.com/404-novel-project/novel-downloader/issues/644#issuecomment-2268886502)
> 
> 用这个解决了

我也遇到了同样的问题，只能下载了每隔一章。之前我也尝试过修改内容，但仍然无法解决。

**Comment by SylviaLe** [comment]
> [#644 (comment)](https://github.com/404-novel-project/novel-downloader/issues/644#issuecomment-2268886502)
> 
> 用这个解决了

我试过了，修改了user-agent，可是没用啊😢还是只能下载每隔一章

**Comment by SylviaLe** [comment]
> > [#644 (comment)](https://github.com/404-novel-project/novel-downloader/issues/644#issuecomment-2268886502)
> > 用这个解决了
> 
> 我也遇到了同样的问题，只能下载了每隔一章。之前我也尝试过修改内容，但仍然无法解决。

刚找到一个workaround，我先下载第1，3，5，7章，然后clear cache，就能下载第2，4，6章，然后把它们集合。有点费劲啊🥲

**Comment by Disolona** [comment]
> > [#644 (comment)](https://github.com/404-novel-project/novel-downloader/issues/644#issuecomment-2268886502)
> > 用这个解决了
> 
> 我试过了，修改了user-agent，可是没用啊😢还是只能下载每隔一章

你有没有安软令牌？
![Screenshot_20240917_173258_Chrome](https://github.com/user-attachments/assets/79f3f588-3872-4886-a824-df1b343a5083)

**Comment by higokei** [comment]
> > > [#644 (comment)](https://github.com/404-novel-project/novel-downloader/issues/644#issuecomment-2268886502)
> > > 用这个解决了
> > 
> > 
> > 我试过了，修改了user-agent，可是没用啊😢还是只能下载每隔一章
> 
> 你有没有安软令牌？ ![Screenshot_20240917_173258_Chrome](https://private-user-images.githubusercontent.com/149059001/368210713-79f3f588-3872-4886-a824-df1b343a5083.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MTQ3NzMsIm5iZiI6MTcyNjYxNDQ3MywicGF0aCI6Ii8xNDkwNTkwMDEvMzY4MjEwNzEzLTc5ZjNmNTg4LTM4NzItNDg4Ni1hODI0LWRmMWIzNDNhNTA4My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QyMzA3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGI1Y2FiODk0ODQ3MTA2MTFiMGYwMWM1M2Q0MWU5ZTExZmYyNjQ4ZDJhMzlhMjlmM2QyYzZkYjdhZmFmMThlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7zb3NEgobzAj2DrLOv64kR2aSeWspmuxSxViLW8JW5Y)

我下载好了，原来是因为我跳过了这一步，非常非常感谢你

**Comment by SylviaLe** [comment]
> > > [#644 (comment)](https://github.com/404-novel-project/novel-downloader/issues/644#issuecomment-2268886502)
> > > 用这个解决了
> > 
> > 
> > 我试过了，修改了user-agent，可是没用啊😢还是只能下载每隔一章
> 
> 你有没有安软令牌？ ![Screenshot_20240917_173258_Chrome](https://private-user-images.githubusercontent.com/149059001/368210713-79f3f588-3872-4886-a824-df1b343a5083.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjY4MDUsIm5iZiI6MTcyNjYyNjUwNSwicGF0aCI6Ii8xNDkwNTkwMDEvMzY4MjEwNzEzLTc5ZjNmNTg4LTM4NzItNDg4Ni1hODI0LWRmMWIzNDNhNTA4My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwMjI4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGM3NzdhNmEzYjYxMzFlNTA5ZTkzY2ZiZDNkMmNkOTIyZGY5YjU0NmMzY2Y1NWNlNWRjYzRmNDQ4YzhjMjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0vnawaqNQTkLqvoLbqo7aB3Z1DGPfVXPwK7o3vVuC64)

有在Windows PC 的办法吗？我没有Android设备啊🥲

**Comment by Disolona** [comment]
> 有在Windows PC 的办法吗？我没有Android设备啊🥲

必须要用Android抓令牌。有人成果用Android模拟器安装来抓令牌，你可以在这里看看评论：
https://greasyfork.org/en/scripts/406070-%E5%B0%8F%E8%AF%B4%E4%B8%8B%E8%BD%BD%E5%99%A8/discussions/216523#comment-456490

**Comment by SylviaLe** [comment]
我拿到了token，也加了token inject script，可是现在什么都下载不到了🥲其实有两个问题：
1，如果我还用这个：
const user_agent = "Mobile "+Date.now();
"user-agent": user_agent,
那下载到我买了的章节它会停止，等了好久也没有更新

2，如果不用const user_agent = "Mobile "+Date.now();，而用最新的修改（这个[commit](https://github.com/404-novel-project/novel-downloader/commit/6918974ff75aa6b8277e9e2ab2b79ab6b6b540e0)），拿什么都下载不了了。打开txt只能看到文案，连免费的章节也没有。
Console的里面是这样的（我买了所有的番外，可是还是null)
![image](https://github.com/user-attachments/assets/c0671c26-017f-4af5-bac2-bbf209427c3c)

@ldm0206 @yingziwu 大佬们有建议怎么解决吗？

**Comment by ldm0206** [comment]
> 我拿到了token，也加了token inject script，可是现在什么都下载不到了🥲其实有两个问题： 1，如果我还用这个： const user_agent = "Mobile "+Date.now(); "user-agent": user_agent, 那下载到我买了的章节它会停止，等了好久也没有更新
> 
> 2，如果不用const user_agent = "Mobile "+Date.now();，而用最新的修改（这个[commit](https://github.com/404-novel-project/novel-downloader/commit/6918974ff75aa6b8277e9e2ab2b79ab6b6b540e0)），拿什么都下载不了了。打开txt只能看到文案，连免费的章节也没有。 Console的里面是这样的（我买了所有的番外，可是还是null) ![image](https://private-user-images.githubusercontent.com/57645987/373055596-c0671c26-017f-4af5-bac2-bbf209427c3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MzY1NDcsIm5iZiI6MTcyNzkzNjI0NywicGF0aCI6Ii81NzY0NTk4Ny8zNzMwNTU1OTYtYzA2NzFjMjYtMDE3Zi00YWY1LWJhYzItYmJmMjA5NDI3YzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA2MTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YjRlOTA4ZTUwMTZjMzI2MDE2MGViNWUxZTM3N2ZkN2FlMTEyOTZmNTQzMWIwMmVhNTRlNzhjNjgxMDFiYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yS8E5yXzocxjlZ7qjj8WZnV5VaKpo50iCNStng21ysg)
> 
> @ldm0206 @yingziwu 大佬们有建议怎么解决吗？

可以先用我这里的 https://github.com/ldm0206/novel-downloader，是没有问题的

**Comment by SylviaLe** [comment]
谢谢大佬回答，可是我试试了，还是没用😢😢

![image](https://github.com/user-attachments/assets/90ae321c-3d70-4222-8f29-14cc6297ffe2)
我买第120章到第145章；console里面下载完119就停了，等一会了还没有更新.

抓取测试也是：
![image](https://github.com/user-attachments/assets/e92092e5-76f2-4b8c-86d6-87ce59f8a1e0)

**Comment by SylviaLe** [comment]
还有，我试试删除[这个script](https://github.com/404-novel-project/novel-downloader?tab=readme-ov-file#token-%E5%A1%AB%E5%86%99)，那原本的问题回来了：可以下载，可是只能下载了每隔一章。

抓取测试：
![image](https://github.com/user-attachments/assets/cc7c82bb-4834-4b3b-9598-8e672e1f561b)

这是下载的txt，你找一找“番外二”；“番外四”；“番外六”等等，没有内容：
[[唧唧喵]社恐心声泄露被大佬们团宠了.txt](https://github.com/user-attachments/files/17249309/default.txt)

**Comment by ldm0206** [comment]
***@***.***）里我看一下On Oct 4, 2024 03:29, Sylvia Le ***@***.***> wrote:
谢谢大佬回答，可是我试试了，还是没用😢😢
image.png (view on web)
我买第120章到第145章；console里面下载完119就停了，等一会了还没有更新.
抓取测试也是：
image.png (view on web)
