### ISSUE TITLE
[Feature Requset] 从pixiv下载小说时不下载章节封面

### ISSUE THREAD

**Issue by CronusLM** [404-novel-project/novel-downloader#653]
**存在问题**
从pixiv下载小说时不下载章节封面

**目标愿景**
增加从pixiv下载注解封面的功能

**参考建议**
无

**补充内容**
无

**Comment by ldm0206** [comment]
有没有小说的链接

**Comment by CronusLM** [comment]
https://www.pixiv.net/novel/series/11693334
就是类似这小说，它既有书籍封面，也有章节封面，我希望能存章节封面。

**Comment by ldm0206** [comment]
你现在看看呢，应该可以了

**Comment by CronusLM** [comment]
谢谢，试了一下可以下载了，之前一个月没下载小说，没注意已经更新了。
