### ISSUE TITLE
[Bug]: 真白萌无法抓取章节

### ISSUE THREAD

**Issue by acalephs** [404-novel-project/novel-downloader#654]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [ ] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

所有真白萌小说均报告
> [initChapters]初始化章节出错，未找到需初始化章节
抓取测试同样找不到章节，一直显示 正在加载章节中……

### 问题发生的网址：

https://masiro.me/admin/novelView?novel_id=1149

### 复现步骤

1 进入页面
2 点击下载

### 期待的行为

下载小说

### 实际的行为

章节抓取失败，下载了空的epub

[Init]开始载入小说下载器……
[Init]当前时间：2024-09-11T22:15:47.158Z
[Init]当前页URL：https://masiro.me/admin/novelView?novel_id=1149
[Init]workerId：2c00d702-484b-4d1a-821d-23be0d51b98b
[Init]当前页Referrer：https://masiro.me/admin/novels?ori=0
[Init]浏览器UA：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
[Init]浏览器语言：zh-CN,zh-TW,en-US,en,zh,zh-Hans
[Init]设备运行平台：Win32
[Init]设备内存：8
[Init]CPU核心数：16
[Init]eval：true, 33
[Init]fetch：true, 29
[Init]XMLHttpRequest：true, 43
[Init]streamSupport：true
[Init]window：249
[Init]localStorage：true
[Init]sessionStorage：true
[Init]Cookie：true
[Init]doNotTrack：1
[Init]enableDebug：false
[Init]ScriptHandler：Violentmonkey
[Init]ScriptHandler version：2.21.0
[Init]Novel-downloader version：5.2.917
[attachment] https://masiro.me/masiroImg/novel-default.jpg?quality=60 下载完成。
[run]下载开始
[]
[preTest]nowRunning: 0
[fflateZip] filename: [川木]成为了吸血鬼于是开始做主播的现代百合.epub, stream: false, streamSaver.supported: true
[initChapters]开始初始化章节
[initChapters] attachmentMode: TM
[initChapters] charset: UTF-8
[initChapters] concurrencyLimit: 3
[initChapters] streamZip: false
[initChapters] needLogin: true
[initChapters] nsfw: false
[initChapters] maxRunLimit: undefined
[initChapters] saveOptions: undefined
[initChapters] book: [object Object]
[initChapters] saveType: undefined
[initChapters] bcWorker: [object BroadcastChannel]
[initChapters] bcWorkerMessages: [object Object]
[initChapters] audio: [object HTMLAudioElement]
[initChapters]初始化章节出错，未找到需初始化章节
[save]保存TXT文件
[stat]小说下载器脚本运行情况统计：
{
  "success": {
    "ncode.syosetu.com": 1,
    "masiro.me": 5
  },
  "failed": {}
}
[stat]success:
    ncode.syosetu.com: 1
    masiro.me: 5
[stat]failed:
[fflateZip] ZIP生成完毕，文件大小：30029
[attachment] https://masiro.me/masiroImg/novel-default.jpg?quality=60 下载完成。

### 小说下载器脚本版本

5.2.917

### 脚本管理器（Tampermonkey/Violentmonkey）版本

2.21.0

### 浏览器名称及版本

Vivaldi	6.9.3447.41

**Comment by ldy2333** [comment]
使用greasyfork未压缩版，修改12847行为
`    aList: document.querySelectorAll(".chapter-ul ul.episode-ul > a"),`
并修改12868行为
`    concurrencyLimit: 1,`
即可正常下载，但由于严重的频率限制，下载速度很慢

**Comment by ldm0206** [comment]
看上去只是下载频率不能多快，对吧？
