### ISSUE TITLE
站点请求：PO18情爱原创

### ISSUE THREAD

**Issue by nuannuanyu** [404-novel-project/novel-downloader#655]
- 站点名称：PO18情爱原创
- 站点 URL：https://www.po18.tw/
- 站点类型：原创网站
- 有无收费章节：有
- 有无如登录墙等额外限制：有强
- 希望添加的理由：很火的网站，而且原创度和创作自由度很高，大多数女性向原创作品都来源于此
- 你认为该站值得阅读的书籍：

**Comment by quitdoing** [comment]
po可以用这个插件https://greasyfork.org/zh-CN/scripts/25068-downloadallcontent，规则在简介页有现成的。
