### ISSUE TITLE
[Bug]: Unable to download a specific finished novel, even though I can download other works without any issues.

### ISSUE THREAD

**Issue by tianyu30-ra** [404-novel-project/novel-downloader#656]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

Initially, I was unable to download any novels at all. I followed the troubleshooting steps from previous posts and resolved the issue, so now I can download normally. However, there is one novel, available at the link below, which I have purchased all chapters for, but I still cannot download it. An error message appears, as shown in the image below, and a log file is automatically generated. Please help me fix this error. Many thanks!
![Capture](https://github.com/user-attachments/assets/edb6fa35-bbd7-4b1a-bd14-b2b47ee80400)
[novel-downloader-1726391193763.log](https://github.com/user-attachments/files/17005171/novel-downloader-1726391193763.log)

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=5297723

### 复现步骤

1. Open the novel's web page.
2. Click the download arrow icon.
3. A message box will pop up at the top of the website, as shown in the image.
![Capture](https://github.com/user-attachments/assets/871435fc-56a7-42b4-9cca-f003e94a1685)
4. Click OK, and a log file will be automatically generated.
5. A website for reporting bugs will open.
6. If you return to the novel’s web page, you will see that the download arrow icon has disappeared.

### 期待的行为

I want to be able to download this novel normally.

### 实际的行为

[novel-downloader-1726391193763.log](https://github.com/user-attachments/files/17005191/novel-downloader-1726391193763.log)

### 小说下载器脚本版本

5.2.917

### 脚本管理器（Tampermonkey/Violentmonkey）版本

v5.1.1

### 浏览器名称及版本

Microsoft Edge Version 128.0.2739.79 (Official build) (64-bit)

**Comment by ldm0206** [comment]
try https://github.com/ldm0206/novel-downloader as a temp solution

**Comment by kikikafka** [comment]
same question. Try https://github.com/ldm0206/novel-downloader as a temp solution,do not work
