### ISSUE TITLE
[Bug]: novels on syosetu.com  and novel18.syosetu.com cannot be downloaded

### ISSUE THREAD

**Issue by GordonRozen** [404-novel-project/novel-downloader#664]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

The novels in syosetu and in cannot be downloaded properly any more. 

### 问题发生的网址：

https://ncode.syosetu.com/n3669fw/ , and https://novel18.syosetu.com/n6426w/

### 复现步骤

1. open the page;
2. click at the download button

### 期待的行为

download start properly

### 实际的行为

the download will not start, either can the novel downloader fetch the full contents, say all the chapters when over 100 (once can be done)

### 小说下载器脚本版本

5.2.917

### 脚本管理器（Tampermonkey/Violentmonkey）版本

Tampermonkey v5.1.1

### 浏览器名称及版本

chrome 129.0.6668.101

**Comment by ldm0206** [comment]
#651

**Comment by GordonRozen** [comment]
Thanks for update, but It seems the issue continues. still It cannot fetch any chapter.

**Comment by ldm0206** [comment]
> Thanks for update, but It seems the issue continues. still It cannot fetch any chapter.

Wait for the developer to reopen his/her PR.
