### ISSUE TITLE
[Bug]: Completely Blank chapter download problem both free and paid novel on JJWXC

### ISSUE THREAD

**Issue by Nabkun** [404-novel-project/novel-downloader#665]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [x] 小说下载器脚本是唯一用户脚本

### 问题描述

I can't download neither paid nor free novel on jjwxc. I have token. I have tried using older version of script on both mobile browser (Kiwi browse, Firefox Browser, Microsoft Edge) and computer browser, but It doesn't work. I have noticed this problem few days ago. I thought it will be fixed or someone would eventually report this issue. There is no solution nor any reported issue on github. So I had to create a new github account only to report this issue.

### 问题发生的网址：

https://www.jjwxc.net/

### 复现步骤

1.open the page; 
2.click at the download button
 
### 期待的行为

Properly download both free and paid chapters.

### 实际的行为

Completely Blank chapter download both free and paid novel.
Bottom is one of the example. I have tried downloading on multiple novel, but shows only blank chapter with chapter number,tilte.
[[福气很大]陛下不可能这么甜(2).txt](https://github.com/user-attachments/files/17476479/2.txt)

### 小说下载器脚本版本

5.2.917 and 5.2.916

### 脚本管理器（Tampermonkey/Violentmonkey）版本

Tampermonkey v5.3.1

### 浏览器名称及版本

Firefox 131.0.3, Microsoft Edge version=130.0.2849.46

**Comment by ovowII** [comment]
我有类似的问题。我做了一些测试。

1/ 第一次尝试不使用 Token => VIP 和非 VIP 部分均无内容。

2/ 第二次尝试使用 token + 上个月修复的脚本（我们更改了 2 件事：
const user_agent = "Mobile "+Date.now();
"user-agent": user_agent,)
结果：
- 可以下载所有非 VIP 章节。我会在这里添加 debug.log，以防万一。
[debug (1).log](https://github.com/user-attachments/files/17530314/debug.1.log)

- 至于 VIP 章节：如果我只下载 1 章，有时它可以像正常一样下载，有时下载栏不会显示。对于这本小说，我可以下载第 19 章（VIP），但选择第 20 章或第 21 章时，下载栏不会显示。
<img width="1352" alt="chap 20" src="https://github.com/user-attachments/assets/f6207b41-9809-49f6-878b-9e78da857c7e">
<img width="1351" alt="ch 21" src="https://github.com/user-attachments/assets/1b2b60e9-528c-46f8-a452-8a48c39a9bdf">


- 如果我选择了 2 个或更多 VIP 章节：下载栏会像下图一样卡住。
<img width="1371" alt="stuck" src="https://github.com/user-attachments/assets/060eb0f4-2e6d-4d2d-9ce6-49708dda89c6">


- 我尝试了其他小说，这次VIP章节都无法下载+下载栏没有出现，因此在这些情况下我无法获取调试日志。

3/ 我尝试了 ldm0206 于 9 月 16 日的新脚本
-所有非VIP章节：正常下载。Debug.log:
[debug new script sep 16.log](https://github.com/user-attachments/files/17530316/debug.new.script.sep.16.log)
- VIP章节：与上述情况相同。

希望大神能再次拯救我们QAQ @ldm0206

**Comment by ldm0206** [comment]
> 我有类似的问题。我做了一些测试。
> 
> 1/ 第一次尝试不使用 Token => VIP 和非 VIP 部分均无内容。
> 
> 2/ 第二次尝试使用 token + 上个月修复的脚本（我们更改了 2 件事： const user_agent = "Mobile "+Date.now(); "user-agent": user_agent,) 结果：
> 
> * 可以下载所有非 VIP 章节。我会在这里添加 debug.log，以防万一。
>   [debug (1).log](https://github.com/user-attachments/files/17530314/debug.1.log)
> * 至于 VIP 章节：如果我只下载 1 章，有时它可以像正常一样下载，有时下载栏不会显示。对于这本小说，我可以下载第 19 章（VIP），但选择第 20 章或第 21 章时，下载栏不会显示。
> 
> <img alt="chap 20" width="1352" src="https://private-user-images.githubusercontent.com/106706630/380419265-f6207b41-9809-49f6-878b-9e78da857c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDk3MzIsIm5iZiI6MTcyOTk0OTQzMiwicGF0aCI6Ii8xMDY3MDY2MzAvMzgwNDE5MjY1LWY2MjA3YjQxLTk4MDktNDlmNi04NzhiLTllNzhkYTg1N2M3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMzMwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTA0YWViZGM2NTg5N2FlZGI0MDFhZTMyZDA3OTM3MWM4ZDlhMGExN2VhOWJiODBkNmQ5ZGQyODhlNzZjMTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-WTmXI2tzuKDTHuR5qtngA0ZnUef3l8oYV3DrI-5XD0"> <img alt="ch 21" width="1351" src="https://private-user-images.githubusercontent.com/106706630/380419271-1b2b60e9-528c-46f8-a452-8a48c39a9bdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDk3MzIsIm5iZiI6MTcyOTk0OTQzMiwicGF0aCI6Ii8xMDY3MDY2MzAvMzgwNDE5MjcxLTFiMmI2MGU5LTUyOGMtNDZmOC1hNDUyLThhNDhjMzlhOWJkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMzMwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDcxM2Q2ZjVkZGJhNzg3NzNiODlhYWRkNTJlZmM4OWQwYjc1OWYyZTIyY2IzNzllZDZlZTgwN2M1ODYwNmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0B69qeZB8qVlEQZDHXx-4DPUyNWzH7enc9Q8WEnIfyI">
> * 如果我选择了 2 个或更多 VIP 章节：下载栏会像下图一样卡住。
> 
> <img alt="stuck" width="1371" src="https://private-user-images.githubusercontent.com/106706630/380419275-060eb0f4-2e6d-4d2d-9ce6-49708dda89c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDk3MzIsIm5iZiI6MTcyOTk0OTQzMiwicGF0aCI6Ii8xMDY3MDY2MzAvMzgwNDE5Mjc1LTA2MGViMGY0LTJlNmQtNGQyZC05Y2U2LTQ5NzA4ZGRhODljNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMzMwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTlmYTkwNDFmM2VhMjNiMzJhNGJjNzIzZWZlZjg3MzUyOWM2OTZiMjkxZmY2ZTVhNjAyM2EwYWQ5NGZhMDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.L5i-kr1bQn9rlmcyI3NDAf9RSL7lm-QDJdq6JBsKJU4">
> * 我尝试了其他小说，这次VIP章节都无法下载+下载栏没有出现，因此在这些情况下我无法获取调试日志。
> 
> 3/ 我尝试了 ldm0206 于 9 月 16 日的新脚本 -所有非VIP章节：正常下载。Debug.log: [debug new script sep 16.log](https://github.com/user-attachments/files/17530316/debug.new.script.sep.16.log)
> 
> * VIP章节：与上述情况相同。
> 
> 希望大神能再次拯救我们QAQ @ldm0206

刚刚修复了一下，你尝试一下，应该可以用了

**Comment by ovowII** [comment]
@ldm0206 谢谢大神，我已经可以正常下载了！您的功德无量！！🙏

**Comment by ldm0206** [comment]
> @ldm0206 谢谢大神，我已经可以正常下载了！您的功德无量！！🙏

:)

**Comment by ovowII** [comment]
@ldm0206 抱歉再次打扰您。这是一个愚蠢的问题，但我只是想确认我只需要重新安装您的脚本（https://github.com/ldm0206/novel-downloader），在会话：[获取脚本：链接]下，对吗？

因为我实际上按下了这篇文章（https://github.com/404-novel-project/novel-downloader/pull/666）上的 1 个新补丁，并能够下载 VIP 章节。有 3 个新补丁 + 其他更新，我不知道如何合并它们，所以我只是随机选择了“patch-4”。

**Comment by Nabkun** [comment]
> > I have similar problem. I did some tests. 
> > 1/ The first attempt is not to use Token => There is no content in VIP and non-VIP parts. 
> > 2/ Second try using token + script fixed last month (we changed 2 things: const user_agent = "Mobile "+Date.now(); "user-agent": user_agent,) Result: 
> > 
> > * All non-VIP chapters can be downloaded. I'll add debug.log here, just in case. 
> >   [debug (1).log ](https://github.com/user-attachments/files/17530314/debug.1.log)
> > * As for the VIP chapters: If I only download 1 chapter, sometimes it downloads like normal, sometimes the download bar doesn't show up. For this novel, I can download Chapter 19 (VIP), but when selecting Chapter 20 or 21, the download bar does not show up.
> > 
> > <img alt="chap 20" width="1352" src="https://private-user-images.githubusercontent.com/106706630/380419265-f6207b41-9809-49f6-878b-9e78da857c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDk3MzIsIm5iZiI6MTcyOTk0OTQzMiwicGF0aCI6Ii8xMDY3MDY2MzAvMzgwNDE5MjY1LWY2MjA3YjQxLTk4MDktNDlmNi04NzhiLTllNzhkYTg1N2M3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMzMwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTA0YWViZGM2NTg5N2FlZGI0MDFhZTMyZDA3OTM3MWM4ZDlhMGExN2VhOWJiODBkNmQ5ZGQyODhlNzZjMTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-WTmXI2tzuKDTHuR5qtngA0ZnUef3l8oYV3DrI-5XD0"> <img alt="ch 21" width="1351" src="https://private-user-images.githubusercontent.com/106706630/380419271-1b2b60e9-528c-46f8-a452-8a48c39a9bdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDk3MzIsIm5iZiI6MTcyOTk0OTQzMiwicGF0aCI6Ii8xMDY3MDY2MzAvMzgwNDE5MjcxLTFiMmI2MGU5LTUyOGMtNDZmOC1hNDUyLThhNDhjMzlhOWJkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMzMwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDcxM2Q2ZjVkZGJhNzg3NzNiODlhYWRkNTJlZmM4OWQwYjc1OWYyZTIyY2IzNzllZDZlZTgwN2M1ODYwNmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0B69qeZB8qVlEQZDHXx-4DPUyNWzH7enc9Q8WEnIfyI">
> > 
> > * If I select 2 or more VIP chapters: the download bar gets stuck like the picture below.
> > 
> > <img alt="stuck" width="1371" src="https://private-user-images.githubusercontent.com/106706630/380419275-060eb0f4-2e6d-4d2d-9ce6-49708dda89c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDk3MzIsIm5iZiI6MTcyOTk0OTQzMiwicGF0aCI6Ii8xMDY3MDY2MzAvMzgwNDE5Mjc1LTA2MGViMGY0LTJlNmQtNGQyZC05Y2U2LTQ5NzA4ZGRhODljNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMzMwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTlmYTkwNDFmM2VhMjNiMzJhNGJjNzIzZWZlZjg3MzUyOWM2OTZiMjkxZmY2ZTVhNjAyM2EwYWQ5NGZhMDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.L5i-kr1bQn9rlmcyI3NDAf9RSL7lm-QDJdq6JBsKJU4">
> > * I tried other novels and this time none of the VIP chapters could be downloaded + the download bar didn't appear, so I couldn't get the debug logs in these cases.
> >  3/ I tried ldm0206's new script on September 16th - all non-VIP chapters: downloaded normally. Debug.log: [ debug new script sep 16.log ](https://github.com/user-attachments/files/17530316/debug.new.script.sep.16.log)
> > 
> > * VIP Chapter: Same as above.
> > 
> > I hope God can save us again QAQ @ldm0206
> 
> Just fixed it, try it, it should work

Where is your fixed version? Can you please share it with me as my previous problem still exist. I only tried to download from chapter 1-10 to see if it works. but it still downloaded blank chapter from 1- 371
[[福气很大]陛下不可能这么甜.txt](https://github.com/user-attachments/files/17531032/default.txt)

**Comment by Nabkun** [comment]
@ldm0206 ldm0206 This script saved me https://github.com/ldm0206/novel-downloader?tab=readme-ov-file 
Thank you so much! I finally found solution of my almost 3 weeks old problem!
@ovowII Thank as well for sharing this script!

**Comment by ldm0206** [comment]
> @ldm0206 抱歉再次打扰您。这是一个愚蠢的问题，但我只是想确认我只需要重新安装您的脚本（[https://github.com/ldm0206/novel-downloader），在会话：[获取脚本：链接]下，对吗？](https://github.com/ldm0206/novel-downloader%EF%BC%89%EF%BC%8C%E5%9C%A8%E4%BC%9A%E8%AF%9D%EF%BC%9A%5B%E8%8E%B7%E5%8F%96%E8%84%9A%E6%9C%AC%EF%BC%9A%E9%93%BE%E6%8E%A5%5D%E4%B8%8B%EF%BC%8C%E5%AF%B9%E5%90%97%EF%BC%9F)

你只需要在[url](https://github.com/ldm0206/novel-downloader/raw/gh-pages/bundle.user.js)更新即可，至于分支的问题，我已经在patch-5中合并了patch1,2,4，而对于一般的使用是不需要关心分支的问题的，（patch-5已经提交PR）

**Comment by ovowII** [comment]
> > @ldm0206 抱歉再次打扰您。这是一个愚蠢的问题，但我只是想确认我只需要重新安装您的脚本（[https://github.com/ldm0206/novel-downloader），在会话：[获取脚本：链接]下，对吗？](https://github.com/ldm0206/novel-downloader%EF%BC%89%EF%BC%8C%E5%9C%A8%E4%BC%9A%E8%AF%9D%EF%BC%9A%5B%E8%8E%B7%E5%8F%96%E8%84%9A%E6%9C%AC%EF%BC%9A%E9%93%BE%E6%8E%A5%5D%E4%B8%8B%EF%BC%8C%E5%AF%B9%E5%90%97%EF%BC%9F)
> 
> 你只需要在[url](https://github.com/ldm0206/novel-downloader/raw/gh-pages/bundle.user.js)更新即可，至于分支的问题，我已经在patch-5中合并了patch1,2,4，而对于一般的使用是不需要关心分支的问题的，（patch-5已经提交PR）

再次感谢大神!!！帮我省了很多麻烦 ( ´⌣`ʃƪ)

**Comment by ldm0206** [comment]
https://github.com/ldm0206/novel-downloader/raw/gh-pages/bundle.user.jsOn Oct 26, 2024 23:06, Nabkun ***@***.***> wrote:


I have similar problem. I did some tests.
1/ The first attempt is not to use Token => There is no content in VIP and non-VIP parts.
2/ Second try using token + script fixed last month (we changed 2 things: const user_agent = "Mobile "+Date.now(); "user-agent": user_agent,) Result:
All non-VIP chapters can be downloaded. I'll add debug.log here, just in case.
debug (1).log As for the VIP chapters: If I only download 1 chapter, sometimes it downloads like normal, sometimes the download bar doesn't show up. For this novel, I can download Chapter 19 (VIP), but when selecting Chapter 20 or 21, the download bar does not show up.
 
If I select 2 or more VIP chapters: the download bar gets stuck like the picture below.

* I tried other novels and this time none of the VIP chapters could be downloaded + the download bar didn't appear, so I couldn't get the debug logs in these cases.
 3/ I tried ldm0206's new script on September 16th - all non-VIP chapters: downloaded normally. Debug.log: [ debug new script sep 16.log ](https://github.com/user-attachments/files/17530316/debug.new.script.sep.16.log)
VIP Chapter: Same as above.
I hope God can save us again QAQ @ldm0206

Just fixed it, try it, it should work

Where is your fixed version? Can you please share it with me as my previous problem still exist. I only tried to download from chapter 1-10 to see if it works. but it still downloaded blank chapter from 1- 371
[福气很大]陛下不可能这么甜.txt
