### ISSUE TITLE
[Bug]: 下载晋江vip章节时会跳过双数章节

### ISSUE THREAD

**Issue by AliciaSword** [404-novel-project/novel-downloader#678]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [ ] 我使用的浏览器是最新版 Chrome 或 Firefox
- [ ] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [ ] 小说下载器脚本是唯一用户脚本

### 问题描述

下载晋江vip章节时会跳过双数章节

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=8751651

### 复现步骤

打开网页点击下载？

### 期待的行为

下载全部章节

### 实际的行为

[Uploading [明目饮][原神+崩铁]工作事件簿.txt…]()

### 小说下载器脚本版本

最新

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.3.1

### 浏览器名称及版本

Chrome最新版

**Comment by ldm0206** [comment]
日志看不了
