### ISSUE TITLE
[Site Request]: ESJ

### ISSUE THREAD

**Issue by Qing-Novel** [404-novel-project/novel-downloader#680]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同的请求存在。
- [X] 我已经确认该网站不可以使用 https://greasyfork.org/zh-CN/scripts/25068-downloadallcontent 或者 https://github.com/dodying/UserJs/blob/master/novel/novelDownloader/novelDownloader3.user.js 下载。

### 站点名称

ESJ

### 站点 URL

https://www.esjzone.me/

### 站点类型

原创网站

### 站点属性

- [ ] 有收费章节存在
- [ ] 所有内容有要求账户登录的限制（未登录不可浏览相关内容）
- [ ] 部分内容（如收费章节）仅限App端可浏览

### 希望添加的理由

之前有cc结尾的esj网站，现在没有了

**Comment by ldm0206** [comment]
#310
