### ISSUE TITLE
[Bug]: Completely blank chapter download problem on JJWXC. script version older and latest 5.2.968 not working

### ISSUE THREAD

**Issue by Nabkun** [404-novel-project/novel-downloader#681]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [ ] 小说下载器脚本是唯一用户脚本

### 问题描述

[[幕僚]穿越大秦当弱A家主 (1).txt](https://github.com/user-attachments/files/17638738/A.1.txt) 

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=8649711

### 复现步骤

I have tried it on both Chrome and Firefox. this problem still persist. A week old version. previous two old and current script version. I have tried all, but none works. I could download properly 5 hour ago. Now it doesn't work again.

### 期待的行为

Script could Download both free and paid chapter (with token) normally.

### 实际的行为

[[幕僚]穿越大秦当弱A家主(2).txt](https://github.com/user-attachments/files/17638881/A.2.txt)

### 小说下载器脚本版本

5.2.968

### 脚本管理器（Tampermonkey/Violentmonkey）版本

Tampermonkey v5.3.1

### 浏览器名称及版本

Firefox and Chrome latest

**Comment by ldm0206** [comment]
设置中"启用调试模式"和"测试视图"，执行下载后，在设置的“日志”中复制全部内容，发送到我的邮箱(ldm669755@gmail.com)，以方便了解具体问题。

**Comment by littlesharkie** [comment]
I think I have the same issue. I tried a few times in different browsers. Sometimes, only free chapters are downloaded. In some other tries, the download would stop halfway until chapter 35/70 and the rest is blank.

The VIP chapter starts from chapter 15/70 and all chapters were purchased. I updated the latest 5.2.963 version.

问题发生的网址：
https://www.jjwxc.net/onebook.php?novelid=9000037

![z6005943860745_2ca630dd9bed29c295a26a535697346f](https://github.com/user-attachments/assets/79d66f6f-22ac-4a71-bf20-b9e97d38cf8a)
