### ISSUE TITLE
[Bug]: Unable to download some title / Blank chapter on JJWXC VIP 

### ISSUE THREAD

**Issue by CheeseBurgerglitch** [404-novel-project/novel-downloader#686]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

The VIP Chapter for some newer title cannot be downloaded.

### 问题发生的网址：

https://www.jjwxc.net/onebook.php?novelid=8802607

### 复现步骤

1. I have try to renew TOKEN but it still doesnt show up in the tester 
2. I have Try other browser, (Firefox and Edge) still same problem.
3. Other older purchased book can be download.
### 期待的行为

[Init]ScriptHandler：Tampermonkey
[Init]ScriptHandler version：5.3.2
[Init]Novel-downloader version：5.2.964
[attachment] https://i8-static.jjwxc.net/tmp/backend/authorspace/s1/9/8733/873227/20240429163423_200_280.jpg 下载完成。
[Chapter]章节名：第 7 章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=8574236&chapterid=7, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第 1 章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=8574236&chapterid=1, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第 100 章, 分卷名：null, URL:http://my.jjwxc.net/onebook_vip.php?novelid=8574236&chapterid=100, VIP:true, Paid:null, isNull:false 解析成功。
[Chapter]章节名：第 10 章, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=8574236&chapterid=10, VIP:false, Paid:null, isNull:false 解析成功。

### 实际的行为

[Init]ScriptHandler：Tampermonkey
[Init]ScriptHandler version：5.3.2
[Init]Novel-downloader version：5.2.964
[attachment] https://s1.imagehub.cc/images/2024/06/03/98977620c576e5543b52659387be8b3b.jpeg 下载完成。
[Chapter]章节名：帮忙, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=8802607&chapterid=7, VIP:false, Paid:null, isNull:false 解析成功。
[Chapter]章节名：卖人情, 分卷名：null, URL:http://my.jjwxc.net/onebook_vip.php?novelid=8802607&chapterid=50, VIP:true, Paid:null, isNull:true 解析成功。
[Chapter]章节名：她好帅, 分卷名：null, URL:http://www.jjwxc.net/onebook.php?novelid=8802607&chapterid=5, VIP:false, Paid:null, isNull:false 解析成功。

### 小说下载器脚本版本

5.2.964

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.3.2

### 浏览器名称及版本

Chrome/130.0.0.0

**Comment by CheeseBurgerglitch** [comment]
Additional :
Try to downgrade to older version 小说下载器脚本版本 to 	v5.2.958.
It managed to download the paid VIP chapter.

**Comment by ldm0206** [comment]
设置中"启用调试模式"和"测试视图"，执行下载后，在设置的“日志”中复制全部内容，发送到我的邮箱([ldm669755@gmail.com](mailto:ldm669755@gmail.com))，以方便了解具体问题。

**Comment by ldm0206** [comment]
似乎是因为账号安全设置导致的，在请求章节时需要额外的验证数据，建议在下载小说时关闭安全验证，下载完毕以后再打开。

**Comment by ldm0206** [comment]
如果还不行，参考最新脚本和readme，配置token 和user_key
