### ISSUE TITLE
站点请求：联合阅读

### ISSUE THREAD

**Issue by myymoon** [404-novel-project/novel-downloader#689]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同的请求存在。
- [X] 我已经确认该网站不可以使用 https://greasyfork.org/zh-CN/scripts/25068-downloadallcontent 或者 https://github.com/dodying/UserJs/blob/master/novel/novelDownloader/novelDownloader3.user.js 下载。

### 站点名称

联合阅读

### 站点 URL

https://xr.unionread.net/column/bookshelf

### 站点类型

原创网站

### 站点属性

- [x] 有收费章节存在
- [ ] 所有内容有要求账户登录的限制（未登录不可浏览相关内容）
- [ ] 部分内容（如收费章节）仅限App端可浏览

### 希望添加的理由

联合阅读是息壤小说网的海外版网站，同时拥有息壤小说网和有毒小说网的全部资源
息壤小说网和有毒小说网限制了网页端无法浏览VIP章节，所以无法使用插件下载，但联合阅读不受此限制，添加支持后可方便的下载息壤和有毒的小说

**Comment by ldm0206** [comment]
他收费章节的结构和免费章节是一样的吗

**Comment by ldm0206** [comment]
> > 他收费章节的结构和免费章节是一样的吗
> 
> 抱歉，我不是很懂这些技术方面的问题，但是免费章节和收费章节点开后的域名都是一样的，里面的内容没什么限制或者乱码加密，用个破解网页限制插件后可以很简单的C+C、V复制下来

等我今天白天有空给你搞搞
