### ISSUE TITLE
[Feature Requset]: 下载pixiv系列小说的设定资料

### ISSUE THREAD

**Issue by CronusLM** [404-novel-project/novel-downloader#693]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同的请求存在。
- [X] 我已经仔细阅读了最新的readme文档，确认文档中没有包含新功能的描述。

### 存在问题

有些pixiv系列小说有设定资料，目前脚本不下载设定资料

### 目标愿景

增加设定资料下载功能

### 参考建议

无

### 补充内容

无

**Comment by ldm0206** [comment]
需要附带上相关的网址

**Comment by CronusLM** [comment]
相关网址
https://www.pixiv.net/novel/series/1433338/glossary

**Comment by ldm0206** [comment]
简单做了一个，样式可能不会太好看，放在简介下面的，如果谁愿意可以在此基础之上美化一下排版什么的，因为我不用这个网站所以不知道标准设定集是什么样子的
