### ISSUE TITLE
[Bug]: 長佩下載失敗

### ISSUE THREAD

**Issue by MarineAq** [404-novel-project/novel-downloader#695]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

小說下載失敗

### 问题发生的网址：

https://www.gongzicp.com/novel-289550.html

### 复现步骤

1.登陆账号
2.已确认购买了本书的VIP章节，此網址為全免 https://www.gongzicp.com/novel-289550.html
3.下载过程中日志显示下载失败

### 期待的行为

正常下载小说。

### 实际的行为

[novel-downloader-1733056175368.log](https://github.com/user-attachments/files/17969184/novel-downloader-1733056175368.log)

### 小说下载器脚本版本

5.2.1008

### 脚本管理器（Tampermonkey/Violentmonkey）版本

Tampermonkey v5.3.2

### 浏览器名称及版本

chrome 版本 131.0.6778.86 (正式版本) (64 位元)

**Comment by ldm0206** [comment]
不是bug，是你下载的太频繁被长佩限制访问了，等一阵子重新下载就可以了，我这里测试是可以正常下载的。
