### ISSUE TITLE
[Site Request]: Bilibili 专栏部分

### ISSUE THREAD

**Issue by abdd22** [404-novel-project/novel-downloader#696]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同的请求存在。
- [X] 我已经确认该网站不可以使用 https://greasyfork.org/zh-CN/scripts/25068-downloadallcontent 或者 https://github.com/dodying/UserJs/blob/master/novel/novelDownloader/novelDownloader3.user.js 下载。

### 站点名称

Bilibili 个人专栏

### 站点 URL

https://www.bilibili.com/read/cv39840808

https://www.bilibili.com/opus/1001144240933175319

### 站点类型

原创网站

### 站点属性

- [ ] 有收费章节存在
- [ ] 所有内容有要求账户登录的限制（未登录不可浏览相关内容）
- [ ] 部分内容（如收费章节）仅限App端可浏览

### 希望添加的理由

最主要的就是小天使蛋牵头的新实教联翻组啦，当然也有其他一些组，他们从LK搬出来了，直接在bilibili的专栏上进行更新工作。

### 你认为该站值得阅读的书籍

欢迎来到实力至上主义的教室 系列。

**Comment by ldm0206** [comment]
在专栏合集中下载，如https://www.bilibili.com/read/readlist/rl723612

**Comment by abdd22** [comment]
不行。因为在合集页面上，我未观察到该脚本（指小说脚本）于本页面（合集页面）上启用。未启用当然就不能下载了。
![bilibili](https://github.com/user-attachments/assets/24e6f0e7-8f00-4592-a941-03c5c564123c)

**Comment by ldm0206** [comment]
> 不行。因为在合集页面上，我未观察到该脚本（指小说脚本）于本页面（合集页面）上启用。未启用当然就不能下载了。 ![bilibili](https://private-user-images.githubusercontent.com/183254541/393104358-24e6f0e7-8f00-4592-a941-03c5c564123c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODQxODgsIm5iZiI6MTczMzQ4Mzg4OCwicGF0aCI6Ii8xODMyNTQ1NDEvMzkzMTA0MzU4LTI0ZTZmMGU3LThmMDAtNDU5Mi1hOTQxLTAzYzVjNTY0MTIzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxMTE4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzQ4Y2JkMTg5OGNmYzdlY2ZmNDE3ODYxNmFhZjg0YmM5YWFkNTk2NjNkMzNjYjZjMWY3NWVmMTc1MzY0YjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JyEHof2mdTCC0nf7CdC9anJwxkUMV65_DyXfD4eqY6I)

你更新没？
