### ISSUE TITLE
[Site Request]: dlsite上的网页阅读器

### ISSUE THREAD

**Issue by abdd22** [404-novel-project/novel-downloader#697]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同的请求存在。
- [X] 我已经确认该网站不可以使用 https://greasyfork.org/zh-CN/scripts/25068-downloadallcontent 或者 https://github.com/dodying/UserJs/blob/master/novel/novelDownloader/novelDownloader3.user.js 下载。

### 站点名称

www.dlsite.com

### 站点 URL

https://www.dlsite.com/comic/work/=/product_id/BJ01761879.html

https://play.dlsite.com/#/work/BJxxxxxx/view

### 站点类型

原创网站

### 站点属性

- [X] 有收费章节存在
- [X] 所有内容有要求账户登录的限制（未登录不可浏览相关内容）
- [ ] 部分内容（如收费章节）仅限App端可浏览

### 希望添加的理由

有太多人在dlsite上面买了书，然后就受制于那个网页阅读器了（就是play.dlsite.com）NGA上面一大群...

正好，近期搞活动，随便找一本免费的来当sample，反正结构和效果应该是一样的。

只能试试看运气了...

### 你认为该站值得阅读的书籍

大型网上电子书店之一，里面什么类型的都有吧。

**Comment by ldm0206** [comment]
不考虑电子书
