### ISSUE TITLE
[Bug]: 69书吧未能获取正确的小说简介

### ISSUE THREAD

**Issue by zrnp** [404-novel-project/novel-downloader#699]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

该插件下载69书吧小说时，简介内容是主页中的最新章内容，而非简介，我觉得应将69书吧对应代码中 `introDom: document.querySelector(".lastcontent"),`改为 `introDom: document.querySelector(".content"),`比较合适

### 问题发生的网址：

https://69shuba.cx/book/46540.htm

### 复现步骤

1. 找到13850行
2. 将该行的.lastcontent改为.content

### 期待的行为

能正确获取小说的简介

### 实际的行为

[[凛冬LIN]诡秘：从战锤归来的通识者.zip](https://github.com/user-attachments/files/18052304/LIN.zip)

### 小说下载器脚本版本

5.2.1014

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.3.2

### 浏览器名称及版本

131.0.6778.109

**Comment by ldm0206** [comment]
下一次你可以直接提交PR，这样的话也方便标记贡献（https://github.com/404-novel-project/novel-downloader/graphs/contributors）
