### ISSUE TITLE
[Bug]: 起点VIP付费章节，已购买但无法下载

### ISSUE THREAD

**Issue by wzg1101** [404-novel-project/novel-downloader#702]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

第70章 接触
=====================

----------

远瞳 · 作家说
（上架啦！！）

上起点中文网支持我，看最新更新[下载App](https://www.qidian.com/chapter/1041604040/811017450/)

第71章 了解更多
=========================

### 问题发生的网址：

https://www.qidian.com/book/1041604040/

### 复现步骤

1.【设置】勾选“启用调试模式。（输出更详细日志）”，“下载Txt文件”， “启用测试视图”
2.【自定义筛选条件】，输出“70-71”，选择两章VIP已付费章节
3.【抓取测试】，输出“70”或“71”，预览中看不到付费章节内容
4.下载时，70和71章无法获取

### 期待的行为

可正常下载付费章节

### 实际的行为

[[作者_远瞳]异度旅社.txt](https://github.com/user-attachments/files/18133895/_.txt)
[debug.log](https://github.com/user-attachments/files/18133896/debug.log)

### 小说下载器脚本版本

5.2.1018

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.3.3

### 浏览器名称及版本

Chrome 版本 131.0.6778.140（正式版本） （64 位）

**Comment by ldm0206** [comment]
看上去是VIP章节不随着页面一起加载的原因，我看看能不能修复
