### ISSUE TITLE
[Bug]: 海棠文化线上文学城已订阅章节仅有标题，正文空白

### ISSUE THREAD

**Issue by solas071** [404-novel-project/novel-downloader#705]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [ ] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [ ] 小说下载器脚本是唯一用户脚本

### 问题描述

下载完成后，点开文件发现免费章节正常有标题有正文，已订阅章节仅有章节标题正文空白

### 问题发生的网址：

https://ebook.longmabook.com/?act=showinfo&bookwritercode=EB20230827043308884972&bookid=225480&pavilionid=a

### 复现步骤

1.以订阅过章节的账号登录
2.点击下载按键
3.文件完成下载

### 期待的行为

正常运行，正常下载完整章节。

### 实际的行为

正常下载文件，订阅章节为空白
[debug.log](https://github.com/user-attachments/files/18160882/debug.log)

### 小说下载器脚本版本

5.2.1023

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.3.3

### 浏览器名称及版本

Edge131.0.2903.99

**Comment by ldm0206** [comment]
谁有VIP账号可供测试的，或者可以自己修一下的？
