### ISSUE TITLE
[Bug]: 海棠文化线上文学城章末已敲彩蛋无法下载

### ISSUE THREAD

**Issue by solas071** [404-novel-project/novel-downloader#706]
### 必要条件

- [X] 我已经搜索 issue 区，并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [X] 我使用的浏览器是最新版 Chrome 或 Firefox
- [ ] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [ ] 小说下载器脚本是唯一用户脚本

### 问题描述

全文免费
点击下载按键后，正常下载。
彩蛋显示为“本章含有彩蛋，但并未敲开。”

### 问题发生的网址：

https://ebook.longmabook.com/?act=showinfo&bookwritercode=EB20190619120231213192&bookid=72428&pavilionid=a

### 复现步骤

1.以订阅过章节的账号登录
2.点击下载按键
3.文件完成下载

### 期待的行为

正常运行，正常下载。

### 实际的行为

正常下载文件，彩蛋内容显示为“本章含有彩蛋，但并未敲开。”
[debug.log](https://github.com/user-attachments/files/18161115/debug.log)

### 小说下载器脚本版本

5.2.1023

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.3.3

### 浏览器名称及版本

Edge131.0.2903.99

**Comment by solas071** [comment]
![image](https://github.com/user-attachments/assets/df02457e-06e2-422d-983a-9de429c025ed)

**Comment by ldm0206** [comment]
> ![image](https://private-user-images.githubusercontent.com/132669722/396419447-df02457e-06e2-422d-983a-9de429c025ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjQ4NjAsIm5iZiI6MTczNDQyNDU2MCwicGF0aCI6Ii8xMzI2Njk3MjIvMzk2NDE5NDQ3LWRmMDI0NTdlLTA2ZTItNDIyZC05ODNhLTlkZTQyOWMwMjVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QwODM2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2I1NmRkZDRiNzQ1YTdlZWRhYTUwN2I2MzhmZDQ4ZmNmMzBlYjU2YTVmMzYxZmFlNjVjZTE5MzQ2MWM5MjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pcD6Zrt_-Uh1qW48zX4pRGL7veOwd2EOtq_3_3Z6HJc)

需要更新脚本
