### ISSUE TITLE
[Bug]: 在esjzone网站上下载小说时，时间一长就失败。

### ISSUE THREAD

**Issue by 606715** [404-novel-project/novel-downloader#709]
### 必要条件

- [X] 我已经仔细阅读了最新的 readme 文档，并确认文档中没有解决此 Bug 的方法。
- [X] 我已经搜索 issue 区（包含已关闭的 issue），并确定没有相同问题存在。
- [X] 我已经尝试将脚本升级至最新版本，但问题仍存在。
- [X] 在尝试下载付费章节前，我已经购买了相应付费章节。

### 当我尝试复现issue时……

- [ ] 我使用的浏览器是最新版 Chrome 或 Firefox
- [X] 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
- [X] 小说下载器脚本是唯一用户脚本

### 问题描述

在esjzone点击下载，长时间得不到回应。

### 问题发生的网址：

https://www.esjzone.cc/

### 复现步骤

第一步，打开网站。第二步，点击下载。

### 期待的行为

点击下载之后马上就能下载，不再长时间等待。

### 实际的行为

[novel-downloader-1734527605968.log](https://github.com/user-attachments/files/18182720/novel-downloader-1734527605968.log)

[ ] 

### 小说下载器脚本版本

5.2.1027

### 脚本管理器（Tampermonkey/Violentmonkey）版本

5.3.6233

### 浏览器名称及版本

Microsoft Edge131.0.2903.99

**Comment by ldm0206** [comment]
不支持直接在论坛主页下载（https://www.esjzone.cc/detail/1610937935.html），必须要进入某个具体的小说页面下载（如https://www.esjzone.cc/detail/1728664873.html）。

此问题已有人反馈过，见 https://github.com/404-novel-project/novel-downloader/issues/690，因为域名结构差不多，自行避免即可。
